---
- name: Create cds user
  ansible.builtin.user:
    name: cds
    home: /srv/cds
    shell: "/usr/bin/bash"

- name: Make sure the .ssh directory exists
  ansible.builtin.file:
    path: /srv/cds/.ssh
    state: directory
    mode: "0700"
    owner: cds
    group: cds

- name: Give cds user the root authorized_keys2
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys2
    dest: /srv/cds/.ssh/authorized_keys2
    owner: cds
    group: cds
    mode: '0644'

- name: Ensure id_ed25519 key for cds@cds
  community.crypto.openssh_keypair:
    path: /srv/cds/.ssh/id_ed25519
    type: ed25519
    owner: cds
    group: cds

- name: Generate ssh cert for the key we just made
  ansible.builtin.include_role:
    name: ssh_ca
    tasks_from: user
  vars:
    ssh_key_to_sign: /srv/cds/.ssh/id_ed25519.pub
    ssh_principal: "cds@{{ inventory_hostname }}"

- name: Disable nginx because the cds runs on those ports
  ansible.builtin.systemd:
    name: nginx
    state: stopped
    enabled: false
    masked: true

- name: Create CDS directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: cds
    group: cds
    mode: '0755'
  with_items:
    - /srv/cds
    - /var/lib/cds


- name: Check if wlp.CDS is installed
  ansible.builtin.stat:
    path: /srv/cds/wlp/usr/servers
  register: wlp_cds_pkg_installed
  check_mode: false

- name: Download wlp.CDS
  github_release:
    repo: icpctools/icpctools
    asset: "^wlp.CDS-.*\\.zip$"
    version: "{{ cds_version }}"
    dest: /srv/cds/wlp.CDS.zip
  when: not wlp_cds_pkg_installed.stat.exists

- name: Download and unpack full CDS if it doesn't exist
  ansible.builtin.unarchive:
    src: /srv/cds/wlp.CDS.zip
    remote_src: true
    dest: /srv/cds
    owner: cds
    group: cds
  when: not wlp_cds_pkg_installed.stat.exists

- name: Check if cds.war exists
  ansible.builtin.stat:
    path: /srv/cds/CDS.war
  register: cds_war
- name: Download CDS itself
  github_release:
    repo: icpctools/icpctools
    asset: "^CDS-.*\\.zip$"
    version: "{{ cds_version }}"
    dest: /srv/cds/CDS.zip
  register: cds_zip_download
- name: Download and unpack CDS war to /srv/cdspackage # noqa: command-instead-of-module no-changed-when
  ansible.builtin.shell: >
    unzip -jo /srv/cds/CDS.zip '*/CDS.war' -d /srv/cds/
  when: cds_zip_download.changed or not cds_war.stat.exists
  register: updated_war

- name: Make sure the cds directory exists
  ansible.builtin.file:
    path: /mnt/{{ ansible_hostname }}/cds
    state: directory
    mode: '0755'
    owner: cds
    group: cds

- name: Check if CDS repo is cloned already
  ansible.builtin.stat:
    path: /mnt/{{ ansible_hostname }}/cds/contest_repo
  register: cds_repo_cloned
    # check_mode: false

- name: Clone the contest repo
  become: true
  become_user: cds
  ansible.builtin.git: # noqa: latest[git]
    repo: "{{ cds_contest_git_repo }}"
    dest: /mnt/{{ ansible_hostname }}/cds/contest_repo
  when: not cds_repo_cloned.stat.exists

- name: Create contests config directory
  ansible.builtin.file:
    path: /srv/cds/contests
    state: directory
    owner: cds
    group: cds
    mode: '0755'

- name: Include cds_instance yaml now
  ansible.builtin.include_tasks: cds_instance.yml
  vars:
    cds_name: "{{ outeritem.key }}"
    cds_instance: "{{ outeritem.value }}"
    needs_restart: updated_war.changed
  with_dict: "{{ cds_config }}"
  loop_control:
    loop_var: outeritem
