---
- name: Create autostart file for things
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Type=Application
      Exec=touch /tmp/vlc-restart-screen
      NoDisplay=true
    dest: /etc/xdg/autostart/vlc-restart-screen.desktop
    mode: "0644"

- name: Create a systemd path activation to restart vlc
  ansible.builtin.copy:
    content: |
      [Path]
      PathChanged=/tmp/vlc-restart-screen
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/vlc-restart-screen.path
    mode: "0644"

- name: Create systemd vlc-restart-screen service
  ansible.builtin.copy:
    dest: /etc/systemd/system/vlc-restart-screen.service
    content: |
      [Unit]
      Description=Restart vlc-screen (to make sure it's happy)

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c "systemctl restart vlc-screen"
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Make sure systemd is loaded
  ansible.builtin.service:
    enabled: true
    state: started
    name: "{{ item }}"
  loop:
    - vlc-restart-screen.service
    - vlc-restart-screen.path
