---
- name: Deploy icpc_xhost_allow
  ansible.builtin.copy:
    content: |
      #
      xhost + local:
    dest: /etc/X11/Xsession.d/36x11-icpc_xhost_allow
    owner: root
    group: root
    mode: '0644'
- name: Copy a smart start-vlc-screen script (it detects active xorg sessions)
  ansible.builtin.copy:
    src: start-vlc-screen
    dest: /usr/local/bin/start-vlc-screen
    mode: 0755
    owner: root
    group: root

- name: Deploy vlc-screen.service
  ansible.builtin.template:
    src: vlc-screen.service.j2
    dest: /lib/systemd/system/vlc-screen.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart vlc-screen

- name: Install QSV required packages (for hw accel encode/decode)
  ansible.builtin.apt:
    pkg:
      - libmfx-gen1.2
- name: Add camera to the render group (so it has access for HW accelerated encoding/decoding)
  ansible.builtin.user:
    name: camera
    groups: render
    append: true
- name: Deploy vlc-webcam.service
  ansible.builtin.template:
    src: vlc-webcam.service.j2
    dest: /lib/systemd/system/vlc-webcam.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart vlc-webcam
- name: Enable and start vlc-screen.service
  ansible.builtin.service:
    name: vlc-screen
    enabled: true
   # state: started
- name: Enable and start vlc-webcam.service
  ansible.builtin.service:
    name: vlc-webcam
    enabled: true
   # state: started

- name: Create autostart file for things
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Type=Application
      Exec=touch /tmp/vlc-restart-screen
      NoDisplay=true
    dest: /etc/xdg/autostart/vlc-restart-screen.desktop
    mode: "0644"

- name: Create a systemd path activation to restart vlc
  ansible.builtin.copy:
    content: |
      [Path]
      PathChanged=/tmp/vlc-restart-screen
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/vlc-restart-screen.path
    mode: "0644"

- name: Create systemd vlc-restart-screen service
  ansible.builtin.copy:
    dest: /etc/systemd/system/vlc-restart-screen.service
    mode: "0644"
    content: |
      [Unit]
      Description=Restart vlc-screen (to make sure it's happy)

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c "systemctl restart --no-block vlc-screen"

      [Install]
      WantedBy=multi-user.target

- name: Make sure systemd is loaded
  ansible.builtin.service:
    enabled: true
    name: "{{ item }}"
    state: started
  loop:
    - vlc-restart-screen.service
    - vlc-restart-screen.path
