---

- name: Ensure packages that are needed for backup hosts are installed
  ansible.builtin.apt:
    pkg:
      - iptables
      - cups
      - rsyslog
      - bash
      - perl
      - tcsh
      - fping
      - libproc-processtable-perl
      - exfat-fuse
      - awscli
      - python3.10-venv
      - git-cola
      - python3-passlib
        # consider adding these to the iso
      - iotop
      - jq
      - htop
      - curl
      - vim
    state: present

- name: Enable DNS bits in resolved.conf
  ansible.builtin.replace:
    path: /etc/systemd/resolved.conf
    regexp: '^[#]?DNS=.*'
    replace: 'DNS=8.8.8.8 8.8.4.4'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Systemd-resolved

- name: Copy per contest hosts to /etc/hosts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/hosts
    mode: '0644'
  with_first_found:
    - files/hosts.{{ contest }}.new
    - files/hosts.new
  notify: Restart dnsmasq

- name: Install rsyslog.d config
  ansible.builtin.copy:
    src: files/40-backup.conf
    dest: /etc/rsyslog.d/40-backup.conf
    mode: '0644'
  notify:
    - Rsyslog

# Overwrite the default rsyslog.conf file with our custom one
# It switches weekly to daily, and adds a couple extra logfiles
# to monitor.
- name: Install logrotate.d config
  ansible.builtin.copy:
    src: files/icpc-logrotate.conf
    dest: /etc/logrotate.d/rsyslog
    mode: '0644'
  notify:
    - Logrotate

- name: Update iptables.rules
  ansible.builtin.template:
    src: templates/iptables.rules.j2
    dest: /etc/iptables.rules
    mode: '0644'
  notify:
    IptablesLoad

- name: Create contest directory if it does not exist
  ansible.builtin.file:
    path: /root/contest/backup/scripts
    state: directory
    mode: '0755'

- name: Install and start backup_watchdog
  block:
    - name: Install backup_watchdog
      ansible.builtin.copy:
        src: backup_watchdog
        dest: /usr/local/sbin/backup_watchdog
        mode: '0755'
      notify: Backup_watchdog
    - name: Install backup_watchdog.service
      ansible.builtin.copy:
        src: backup_watchdog.service
        dest: /etc/systemd/system/backup_watchdog.service
        mode: '0644'
      notify: Backup_watchdog
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        enabled: true
        daemon_reload: true
        name: backup_watchdog.service

- name: Install contest/backup/scripts
  ansible.builtin.copy:
    src: files/{{ item.name }}
    dest: /root/contest/backup/scripts/{{ item.name }}
    mode: "{{ item.mode | default('0755') }}"
    owner: root
    group: root
  loop:
    - {name: par}
    - {name: sh.do_startbackup}
    - {name: sh.backupclient}
    - {name: exclude.lst, mode: "0644"}

- name: Install ssh config
  ansible.builtin.copy:
    src: files/root.ssh.config
    dest: /root/.ssh.config
    mode: '0600'
    owner: root
    group: root

- name: Ensure config.pl
  ansible.builtin.template:
    src: config.pl.j2
    dest: /root/contest/backup/scripts/config.pl
    mode: '0600'
    owner: root
    group: root
