---
- name: Check if the printer exists
  ansible.builtin.command: lpstat -p {{ printer_name }}
  register: lpstat
  changed_when: false
  ignore_errors: true

- name: Lpadmin add a printer
  # use keith's icpc-banner instead (on the server side)
  ansible.builtin.command: lpadmin -p {{ printer_name }} -E -v ipp://printsrv:631/{{ device_uri }} -L "{{ inventory_hostname }}"
  when: lpstat.rc != 0
  changed_when: false

- name: Set the printer as default
  ansible.builtin.command: lpadmin -d {{ printer_name }}
  when: lpstat.rc != 0
  changed_when: false
