---
printsrv_contest_id: finals

# useful to disable during imaging phase
contest_printer_enabled: true

# this also supports a model: (defaults to everywhere)
printserver_print_config:
  - {name: judgeprint, is_default: false}
  - {name: systemsprint, is_default: true}
  - {name: balloonprint, is_default: false}
  - {name: teamprint1, contestprinter: true}
  - {name: teamprint2, contestprinter: true}
