- name: Create presentation client user
  ansible.builtin.user:
    name: p
    home: /p
    uid: 17263
    shell: "/usr/bin/bash"

- name: Add run script for p
  ansible.builtin.template:
    src: pres_client_run.sh.j2
    dest: /p/run
    owner: p
    group: p
    mode: '0755'

- name: Add .xsessionrc script for p
  ansible.builtin.copy:
    content: |
      /p/run
      exit 0
    dest: /p/.xsessionrc
    owner: p
    group: p
    mode: '0755'

- name: Check if presclient is installed
  ansible.builtin.stat:
    path: /p/client.sh
  register: pres

- name: Download p100
  github_release:
    repo: icpctools/icpctools
    asset: "^presentations-.*\\.zip$"
    version: "{{ p100_version }}"
    dest: /p/p100.zip

- name: Copy presentations zip
  ansible.builtin.copy:
    src: files/presentations.zip
    dest: /p/p100.zip

- name: Unpack the client
  ansible.builtin.unarchive:
    src: "/p/p100.zip"
    remote_src: true
    dest: /p/
    owner: p
    group: p
