---
- name: Configure contestant machines to undo challenge
  hosts: contestants
  gather_facts: false

  roles:
    - role: firefox_desktop
    - role: iptablesrules

  tasks:
    - name: Remove open-tests
      ansible.builtin.file:
        state: absent
        path: /home/{{ inventory_hostname }}/Desktop/open-tests

    - name: Disable DNS bits in resolved.conf
      ansible.builtin.replace:
        path: /etc/systemd/resolved.conf
        regexp: '^[#]?DNS=.*'
        replace: '#DNS='
        owner: root
        group: root
        mode: '0644'

    - name: Enable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
        masked: true

  handlers:
    - name: Systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
