---
- name: Disable autologin
  hosts: contestants
  gather_facts: false
  tasks:
    - name: Disable autologin to user p
      ansible.builtin.file:
        path: /etc/lightdm/lightdm.conf.d/p100.conf
        state: absent
