---
- name: Create the user the named hosts for contest
  gather_facts: false
  hosts: contestants
  vars:
    contest: TODO


  tasks:
    - name: Clear /home
      ansible.builtin.command: "/root/sh.clear_home"
      changed_when: false

    - name: Clear /etc/skel/Desktop/samps
      ansible.builtin.file:
        state: absent
        path: /etc/skel/Desktop/samps

    - name: Check if contest-samples.zip exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "files/{{ contest }}-samples.zip"
      register: samples_zip

    - name: If contest-samples.zip exist extract it
      when: samples_zip.stat.exists
      block:
        - name: Create /etc/skel/Desktop/samps
          ansible.builtin.file:
            path: /etc/skel/Desktop/samps
            state: directory
            mode: '0755'
            owner: root
            group: root

        - name: Deploy contest-samples.zip to /etc/skel/Desktop/samps
          ansible.builtin.unarchive:
            src: "{{ contest }}-samples.zip"
            dest: /etc/skel/Desktop/samps

    - name: Create the user on named host
      ansible.builtin.user:
        name: "{{ inventory_hostname }}"
        password: "{{ users[inventory_hostname] | password_hash('sha512') }}"
        comment: "{{ inventory_hostname }},,,"
        shell: /bin/bash
        group: teams
        create_home: true

    - name: Configure lightdm ccs greeter
      ansible.builtin.copy:
        content: |
          [General]
          ;greeter-icon-theme=oxygen
          greeter-background-image=/usr/share/backgrounds/ICPCLogo-greeter.png
          loginform-offset-x=50%
          loginform-offset-y=40%
          ccs-contest-api-url={{ ccs_contest_url }}
          ccs-autologin-username={{ inventory_hostname }}
          ccs-autologin-password={{ users[inventory_hostname] }}
          ;ccs-start-minimum-msec=500
          ;ccs-team-name={{ inventory_hostname }}
          ;ccs-team-label-color=white
          ;ccs-team-label-shadow-color= ;unset
        dest: /etc/lightdm/lightdm-qt5-greeter.conf
        owner: root
        group: root
        mode: '0600'
      diff: false
