---
- name: Create the user the named hosts for contest on constestants
  gather_facts: false
  hosts: contestants
  vars:
    contest: &contest TODO
    accounts_yaml: /root/contest_repo/passwork/{{ contest }}/linux_accounts.yaml

  tasks:
    - name: Clear /home
      ansible.builtin.command: "/root/sh.clear_home"
      changed_when: false

    - name: Clear /etc/skel/Desktop/samps
      ansible.builtin.file:
        state: absent
        path: /etc/skel/Desktop/samps

    - name: Check if contest-samples.zip exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "files/{{ contest }}-samples.zip"
      register: samples_zip

    - name: If contest-samples.zip exist extract it
      when: samples_zip.stat.exists
      block:
        - name: Create /etc/skel/Desktop/samps
          ansible.builtin.file:
            path: /etc/skel/Desktop/samps
            state: directory
            mode: '0755'
            owner: root
            group: root

        - name: Deploy contest-samples.zip to /etc/skel/Desktop/samps
          ansible.builtin.unarchive:
            src: "{{ contest }}-samples.zip"
            dest: /etc/skel/Desktop/samps

    - name: Fetch the team password to a fact
      ansible.builtin.set_fact:
        team_password: "{{ 'passw0rd' if 'spares' in group_names else ((lookup('file', accounts_yaml)|from_yaml)['users'][inventory_hostname])}}"
    - name: Create the user on named host
      ansible.builtin.user:
        name: "{{ inventory_hostname }}"
        password: "{{ team_password | password_hash('sha512') }}"
        comment: "{{ inventory_hostname }},,,"
        shell: /bin/bash
        group: teams
        create_home: true
    - name: Create a .netrc file for pc2
      ansible.builtin.copy:
        dest: /home/{{ inventory_hostname }}/.netrc
        content: "machine pc2 login {{ inventory_hostname }} password {{ team_password }}\n"
        owner: "{{ inventory_hostname }}"
        group: teams
        mode: 0600
      when: ccs == "pc2"

- name: Configure the human_judges
  gather_facts: false
  hosts: human_judges
  vars:
    contest: *contest

  tasks:
    - name: Clear /etc/skel/Desktop/samps
      ansible.builtin.file:
        state: absent
        path: /etc/skel/Desktop/samps

    - name: Clear /home/icpc/Desktop/samps
      ansible.builtin.file:
        state: absent
        path: /home/icpc/Desktop/samps

    - name: Check if contest-samples.zip exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "files/{{ contest }}-samples.zip"
      register: samples_zip

    - name: If contest-samples.zip exist extract it
      when: samples_zip.stat.exists
      block:
        - name: Create /etc/skel/Desktop/samps
          ansible.builtin.file:
            path: /etc/skel/Desktop/samps
            state: directory
            mode: '0755'
            owner: root
            group: root

        - name: Deploy contest-samples.zip to /etc/skel/Desktop/samps
          ansible.builtin.unarchive:
            src: "{{ contest }}-samples.zip"
            dest: /etc/skel/Desktop/samps

        - name: Create /home/icpc/Desktop/samps
          ansible.builtin.file:
            path: /home/icpc/Desktop/samps
            state: directory
            mode: '0755'
            owner: icpc
            group: icpc

        - name: Deploy contest-samples.zip to /home/icpc/Desktop/samps
          ansible.builtin.unarchive:
            src: "{{ contest }}-samples.zip"
            dest: /home/icpc/Desktop/samps
            owner: icpc
            group: icpc
