---
- name: Reboot to a netboot
  gather_facts: false
  hosts: contestants
  vars:
    efibootmgr: true
    dellcctk: false # use the dell command to force pxe boot next boot
    efibootmgr_search: 'UEFI: PXE IPv4'
  tasks:
    - name: Install efibootmgr
      ansible.builtin.package:
        name: efibootmgr
        state: present
      when: efibootmgr

    - name: Figure out the network boot device
      ansible.builtin.shell:
        cmd: >
          set -o pipefail &&
          efibootmgr |
          grep '{{ efibootmgr_search }}' |
          cut -f1 -d' ' |
          sed s/^Boot// |
          tr -d '*'
        executable: /bin/bash
      register: net_boot_device
      changed_when: false

    - name: Efibootmgr to force a netboot
      ansible.builtin.command: efibootmgr -n {{ net_boot_device.stdout }}
      changed_when: false
      when: efibootmgr

    - name: Dell cctk to force a netboot
      ansible.builtin.command: /opt/dell/dcc/cctk --ForcePxeNextBoot=Enabled
      changed_when: false
      when: dellcctk

    - name: Reboot
      ansible.builtin.command: reboot # noqa: ignore-errors
      failed_when: false # ignore failures, because reboot will disconnect us before the command returns
      changed_when: false
      ignore_errors: true
