---
- name: Run ab on hosts
  gather_facts: false
  hosts: contestants

  tasks:
    - name: Run apache-util
      ansible.builtin.command: "ab -n 1000 -c 100 https://icpcdhaka.contest.codeforces.com/static/js/jquery-1.8.3.js"
      register: ab
      changed_when: false

    - name: Output of ab
      ansible.builtin.debug:
        var: ab.stdout_lines
