---
- name: Playbook to enable autologin
  hosts: contestants
  gather_facts: false
  tasks:
    - name: Enable autologin to team user
      ansible.builtin.copy:
        content: |
          [daemon]
          AutomaticLoginEnable = true
          AutomaticLogin = {{ inventory_hostname }}
          [security]

          [xdmcp]

          [chooser]

          [debug]
        dest: /etc/gdm3/custom.conf
        owner: root
        group: root
        mode: '0644'
    - name: Check if user is currently running
      ansible.builtin.command: pgrep --uid {{ inventory_hostname }}
      register: user_running
      ignore_errors: true
      changed_when: false
    - name: Restart gdm3
      ansible.builtin.systemd:
        name: gdm3
        state: restarted
      when: user_running.rc != 0
