---
- name: Playbook to enable autologin
  hosts: contestants
  gather_facts: false
  serial: 30
  tasks:
    - name: Enable autologin to user p
      ansible.builtin.copy:
        content: |
          [SeatDefaults]
          # Autologin
          autologin-user=p
          autologin-timeout=0
        dest: /etc/lightdm/lightdm.conf.d/p100.conf
        owner: root
        group: root
        mode: '0644'
    - name: Check if p is currently running
      ansible.builtin.command: pgrep --uid p
      register: p_running
      ignore_errors: true
      changed_when: false
    - name: Clear /tmp/org.icpc.tools.cache* dir
      ansible.builtin.file:
        path: /tmp/org.icpc.tools.cache*
        state: absent
      when: p_running.rc != 0
    - name: Restart lightdm
      ansible.builtin.systemd:
        name: lightdm
        state: restarted
      when: p_running.rc != 0
