---
- name: Playbook to enable ccs autologin on the lightdm greeter
  hosts: contestants
  gather_facts: false
  tasks:
    - name: Enable ccs autologin
      ansible.builtin.lineinfile:
        line: greeter-session=lightdm-qt5-greeter
        regexp: ^greeter-session
        dest: /etc/lightdm/lightdm.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart lightdm
  handlers:
    - name: Restart lightdm
      ansible.builtin.systemd:
        name: lightdm
        state: restarted
