---
- name: Configure contestant machines for challenge
  hosts: contestants
  gather_facts: false
  vars:
    firefox_default: https://icpcluxor.contest.codeforces.com/
    users:
      # spares
      team46132: passw0rd
      team46133: passw0rd
      team46134: passw0rd
      team46150: passw0rd
      team47137: passw0rd
      team47138: passw0rd
      team47150: passw0rd


  roles:
    - role: firefox_desktop

  tasks:
    - name: Clear /home
      ansible.builtin.command: "/root/sh.clear_home"

    - name: Make sure /etc/skel/Desktop/samps doesn't exist
      ansible.builtin.file:
        state: absent
        path: /etc/skel/Desktop/samps

    - name: Create the user on named host
      ansible.builtin.user:
        name: "{{ inventory_hostname }}"
        password: "{{ users[inventory_hostname] | password_hash('sha512') }}"
        comment: "{{ inventory_hostname }},,,"
        shell: /bin/bash
        groups: teams
        create_home: true

    - name: Delete the domjudge/ccs shortcut from the applications menu
      ansible.builtin.file:
        state: absent
        path: /usr/share/applications/ccs.desktop

    - name: Install "open-tests.zip"
      ansible.builtin.unarchive:
        src: files/challenge/open-tests.tar.gz
        dest: /home/{{ inventory_hostname }}/Desktop
        owner: "{{ inventory_hostname }}"
        group: teams

    - name: Enable DNS bits in resolved.conf
      ansible.builtin.replace:
        path: /etc/systemd/resolved.conf
        regexp: '^[#]?DNS=.*'
        replace: 'DNS=8.8.8.8 8.8.4.4'
        owner: root
        group: root
        mode: '0644'
      notify:
        - Systemd-resolved

    - name: Enable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: started
        enabled: true
        masked: false


    # probably we need to explicitly allow access on the network firewall allowing the team machines
    # to contact the CDS, so that p100 works properly
    - name: Install firewall rules
      notify: Iptables load
      ansible.builtin.copy:
        group: root
        owner: root
        mode: "0644"
        dest: /etc/iptables.rules
        content: |
          # Generated by iptables-save v1.8.7 on Mon Apr 15 18:58:28 2024
          *filter
          :INPUT ACCEPT [12:930]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [65:23036]

          -N accept-in-log
          -A accept-in-log -j LOG --log-level 4 --log-prefix "accept-in-log:"
          -A accept-in-log -j ACCEPT
          -N accept-out-log
          -A accept-out-log -j LOG --log-level 4 --log-prefix "accept-out-log:"
          -A accept-out-log -j ACCEPT
          -N drop-n-log
          -A drop-n-log -j LOG -m limit --limit 5/m --limit-burst 7 --log-level 4 --log-prefix "DENIED:"
          -A drop-n-log -j DROP

          -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          -A OUTPUT -p udp -m multiport --dports 53 -j ACCEPT
          -A OUTPUT -d 10.3.3.220/32 -p tcp -m multiport --dports 80,443,53 -j drop-n-log
          -A OUTPUT -d 10.3.3.219/32 -p tcp -m multiport --dports 80,443,53 -j drop-n-log
          -A OUTPUT -d 10.3.3.218/32 -p tcp -m multiport --dports 80,443,53 -j drop-n-log
          -A OUTPUT -d 10.3.3.217/32 -p tcp -m multiport --dports 80,443,53 -j drop-n-log
          -A OUTPUT -d 10.3.3.216/32 -p tcp -m multiport --dports 80,443,53 -j drop-n-log
          -A OUTPUT -d 10.3.3.215/32 -p tcp -m multiport --dports 80,443,53 -j drop-n-log
          -A OUTPUT -p tcp -m multiport --dports 80,443,53 -j ACCEPT
          COMMIT
          # Completed on Mon Apr 15 18:58:28 2024

#    - name: Firewall additions input
#      ansible.builtin.iptables:
#        chain: INPUT
#        ctstate: ESTABLISHED,RELATED
#        jump: ACCEPT
#        action: insert
#
#    - name: Firewall additions output tcp
#      ansible.builtin.iptables:
#        chain: OUTPUT
#        protocol: tcp
#        destination_ports:
#          - "80"
#          - "443"
#          - "53"
#        jump: ACCEPT
#        action: insert
#
#    - name: Firewall block domjudge {{ item }}
#      ansible.builtin.iptables:
#        chain: OUTPUT
#        protocol: tcp
#        destination: "{{ item }}"
#        destination_ports:
#          - "80"
#          - "443"
#          - "53"
#        jump: drop-n-log
#        action: insert
#      loop:
#        - "10.3.3.215/32"
#        - "10.3.3.216/32"
#        - "10.3.3.217/32"
#        - "10.3.3.218/32"
#        - "10.3.3.219/32"
#        - "10.3.3.220/32"
#
#    - name: Firewall additions output udp
#      ansible.builtin.iptables:
#        chain: OUTPUT
#        protocol: udp
#        destination_ports:
#          - "53"
#        jump: ACCEPT
#        action: insert

  handlers:
    - name: Iptables load
      ansible.builtin.shell: /etc/network/if-pre-up.d/iptablesload

    - name: Systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
