---
- name: configure contestant machines for challenge
  hosts: contestants
  gather_facts: false

  tasks:
    - name: change firefox to codeforces
      ansible.builtin.copy:
        src: files/challenge.firefox.desktop
        dest: /usr/share/applications/firefox.desktop

    - name: enable DNS bits in resolved.conf
      ansible.builtin.replace:
        path: /etc/systemd/resolved.conf
        regexp: '^[#]?DNS=.*'
        replace: 'DNS=8.8.8.8 8.8.4.4'
        owner: root
        group: root
        mode: '0644'
      notify:
        - systemd-resolved

    - name: enable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: started
        enabled: true
        masked: false

    - name: firewall additions input
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        action: insert

    - name: firewall additions output tcp
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
          - "53"
        jump: ACCEPT
        action: insert

    - name: firewall blocks #2
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: 10.3.3.215/32
        destination_ports:
          - "80"
          - "443"
          - "53"
        jump: drop-n-log
        action: insert

    - name: firewall blocks #1
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: 10.3.3.216/31
        destination_ports:
          - "80"
          - "443"
          - "53"
        jump: drop-n-log
        action: insert

    - name: firewall additions output udp
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: udp
        destination_ports:
          - "53"
        jump: ACCEPT
        action: insert

  handlers:
    - name: systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
