---

- name: Configure grafana
  hosts: grafana
  vars:
    host_type: grafana
  become: true
  roles:
    - role: prometheus_target_all
      tags: prometheus_target_all
    - role: grafana
      tags: grafana
