---
# this needs to be first as ldap requires it
- name: Pre-configure apt
  hosts: all
  roles:
    - role: apt

- name: Configure coachview machines
  hosts: coachview*
  roles:
    - role: coachview

- name: Configure contestant machines
  hosts: contestants
  roles:
    - role: cups
    - role: team
    - role: ldapclient
      tags: ldapclient
      when: ldap_domain is defined
    - role: hyperthreadingdisabled
    - role: reverseproxy
      when: enable_reverseproxy is defined and enable_reverseproxy
    - role: p100
    - role: ccstools
      when: ccs  == "domjudge"
    - role: taskset_run_scripts
    - role: vlc
      when: enable_vlc is defined and enable_vlc
    - role: iptablesrules
    - role: martkeys
      when: disable_martkeys is not defined or not disable_martkeys

  tasks:
    - name: Switch from files to compat in nsswitch
      tags: nsswitch
      ansible.builtin.replace:
        path: /etc/nsswitch.conf
        regexp: '^{{ item }}(.*)files'
        replace: "{{ item }}\\1compat"
        owner: root
        group: root
        mode: '0644'
      loop:
        - passwd
        - group
        - shadow
      notify:
        - Reboot
      when: ldap_domain is defined
    - name: Disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
        masked: true

    - name: Remove icpc user
      ansible.builtin.user:
        name: "icpc"
        state: absent
      when: root_password is defined

    - name: Workaround nautilus auto-mounting
      ansible.builtin.file:
        path: /media
        owner: root
        group: root
        mode: "0700"

    - name: Use policykit to disable mounting for teams
      ansible.builtin.copy:
        dest: /etc/polkit-1/localauthority/50-local.d/disable-udisks.pkla
        content: |
          [Block access to udisks for teams]
          Identity=unix-user:*
          Action=org.freedesktop.udisks2.*
          ResultAny=no
          ResultInactive=no
          ResultActive=no
        mode: '0644'
    - name: Fix gvfsd permission tweaking to disable
      ansible.builtin.file:
        path: /usr/libexec/{{ item }}
        owner: root
        group: root
        mode: "0744"
      loop:
        - "gvfsd-burn"
        - "gvfsd-computer"
        - "gvfsd-localtest"
    - name: Place 21_icpc-disable-automount-schema.gschema.override
      ansible.builtin.copy:
        content: |
          [org.gnome.desktop.media-handling]
          automount-open=false
          automount=false
        dest: /usr/share/glib-2.0/schemas/21_icpc-disable-automount-schema.gschema.override
        owner: root
        group: root
        mode: '0644'
      notify: Glib-compile-schemas
  handlers:
    - name: Glib-compile-schemas
      ansible.builtin.command: glib-compile-schemas /usr/share/glib-2.0/schemas
      changed_when: false
    - name: Reboot
      ansible.builtin.reboot:

- name: Configure ldap server
  hosts: ldapserver
  roles:
    - role: ldapserver
      tags: ldapserver

- name: Send syslogs to `backup`
  hosts: all:!backup
  tasks:
    - name: Point rsyslog to backup
      ansible.builtin.copy:
        content: |
          # ship the important logs to backup
          kern.warning                    @backup
          auth,authpriv.*                 @backup
        dest: /etc/rsyslog.d/70-clients.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart rsyslog
  handlers:
    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted

- name: Lastminute config for all hosts
  hosts: all
  roles:
    - role: firefox_desktop
    - role: stuvusIT.systemd-timesyncd
      timesync_timezone: "{{ timezone }}"
      timesync_ntp_hosts:
        - "{{ baseip }}.208"
        - "{{ baseip }}.209"
        - "{{ baseip }}.210"
      timesync_fallback_ntp_hosts:
        - "{{ baseip }}.208"
        - "{{ baseip }}.209"
        - "{{ baseip }}.210"
      tags: systemd-timesyncd

  vars:
    judging_notes: "{{ 'files/%s.JudgingNotes.%s.pdf'|format(contest_detail, papersize) }}"
    tech_notes: "{{ 'files/%s.TechNotes.%s.pdf'|format(contest_detail, papersize) }}"

  tasks:
    # stat file first
    - name: Get file stat of JudgingNotes to be able to perform a check in the following task
      ansible.builtin.stat:
        path: "{{ judging_notes }}"
      register: judgingnotes

    - name: Copy JudgingNotes.pdf
      ansible.builtin.copy:
        src: "{{ judging_notes }}"
        dest: /usr/share/doc/icpc/JudgingNotes.pdf
        mode: '0644'
      when: judgingnotes.stat.exists

    - name: Get file stat of TechNotes to be able to perform a check in the following task
      ansible.builtin.stat:
        path: "{{ tech_notes }}"
      register: technotes

    - name: Copy TechNotes.pdf
      ansible.builtin.copy:
        src: "{{ tech_notes }}"
        dest: /usr/share/doc/icpc/TechNotes.pdf
        mode: '0644'
      when: technotes.stat.exists

    - name: DOMJudge only bits
      when: ccs == "domjudge"
      block:
        - name: Is contest_detail TeamGuide.pdf available?
          delegate_to: localhost
          ansible.builtin.stat:
            path: files/"{{ contest_detail }}-domjudge-team-manual.pdf"
          register: domjudge_team_manual

        - name: Copy domjudge TeamGuide.pdf (if ccs == domjudge)
          ansible.builtin.copy:
            src: files/"{{ contest_detail }}-domjudge-team-manual.pdf"
            dest: /usr/share/doc/icpc/TeamGuide.pdf
            mode: '0644'
          when: domjudge_team_manual.stat.exists

        - name: Add domjudge to /etc/hosts
          ansible.builtin.lineinfile:
            path: /etc/hosts
            line: "{{ baseip }}.{{ item.ip }}   {{ item.hostname }}" # noqa: no-tabs
            owner: root
            group: root
            mode: '0644'
          loop:
            # TODO make this 215 configurable
            - { ip: 215, hostname: domjudge }
          when: enable_reverseproxy is not defined or not enable_reverseproxy

        - name: Add domjudge doc dir
          ansible.builtin.file:
            path: /usr/share/apps/domjudge
            state: directory
            mode: '0755'

        - name: Add domjudge png
          ansible.builtin.copy:
            src: files/DOMjudgelogo.png
            dest: /usr/share/apps/domjudge/DOMjudgelogo.png
            mode: '0644'

        - name: Add domjudge desktop entry
          ansible.builtin.copy:
            src: files/domjudge.desktop
            dest: /usr/share/applications/domjudge.desktop
            mode: '0644'

    # local accounts bit
    - name: Create group teams
      ansible.builtin.group:
        name: teams
        gid: 3000

    - name: Copy the per contest bits
      ansible.builtin.copy:
        src: "{{ contest }}.teams.tar.gz"
        dest: "/root/{{ contest }}.teams.tar.gz"
        mode: '0600'
    # this should be fixed in the icpc2021 package
    - name: Enable Evince and Evince-preview desktop files
      ansible.builtin.file:
        name: /usr/share/applications/org.gnome.{{ item }}.desktop
        mode: '0644'
      loop:
        - Evince
        - Evince-previewer
    - name: Pre-generate the kernel flags for ansible usage
      ansible.builtin.set_fact:
        procline: "quiet ipv6.disable=1 cgroup_enable=memory swapaccount=1 i915.force_probe=4690"
    - name: Ensure /etc/default/grub has proper GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*$'
        replace: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ procline }}\""
        owner: root
        group: root
        mode: '0644'
      notify:
        - Update grub
        - Reboot
    - name: Ensure /etc/default/grub has proper GRUB_TIMEOUT
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: "GRUB_TIMEOUT=.*"
        replace: "GRUB_TIMEOUT=3"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Update grub

    - name: Update root password (if root_password already crypted)
      ansible.builtin.user:
        name: "root"
        state: present
        password: "{{ root_password }}"
      when:
        - root_password is defined
        - '"$6$" in root_password'
    - name: Update root password (if root_password is cleartext)
      ansible.builtin.user:
        name: "root"
        state: present
        password: "{{ root_password | password_hash('sha512', job_sheet) }}"
      when:
        - root_password is defined
        - '"$6$" not in root_password'

    - name: Get GIT revision
      ansible.builtin.shell: |
          set -o pipefail
          git rev-list --full-history --all --abbrev-commit | head -1
          exit 0
      args:
        executable: /bin/bash
      become: false
      register: git_revision
      delegate_to: 127.0.0.1
      changed_when: false

    - name: Log version of script on client
      community.general.syslogger:
        ident: "lastminute"
        msg: "Ansible applied {{ version }} - ({{ git_revision.stdout }})"
        priority: "notice"
      changed_when: false
  handlers:
    - name: Update grub
      ansible.builtin.command: /usr/sbin/update-grub
      changed_when: false
    - name: Reboot
      ansible.builtin.reboot:

- name: Configure the reverse proxy
  hosts: reverseproxy
  roles:
    - role: reverseproxy
      reverseproxy_server: true
      tags: reverseproxy

- name: Configure the cds
  hosts: cds
  roles:
    - role: cds
      tags: cds

- name: Configure balloonmanager printers
  hosts: balloonmanager
  vars:
    job_sheet: null
    device_uri: 'printers/balloonprinter'
    printer_name: balloonprinter
  roles:
    - role: cups

- name: Configure ccsadmin printers
  hosts: ccsadmin*
  vars:
    job_sheet: null
    device_uri: 'printers/systemsprinter'
    printer_name: systemsprinter
  roles:
    - role: cups

- name: Configure judges printers
  hosts: judge*
  vars:
    job_sheet: null
    device_uri: 'printers/systemsprinter'
    printer_name: systemsprinter
  roles:
    - role: cups

- name: Configure others printers
  hosts: others:!authprint
  vars:
    job_sheet: null
    device_uri: 'printers/systemsprinter'
    printer_name: systemsprinter
  roles:
    - role: cups
