---
- hosts: contestants
  vars:
    host_type: contestant
    version: ansibleconversion0.1
    baseip: 10.3.3
  roles:
    - role: timezone
      tags: timezone
    - role: packages
      tags: packages
  tasks:
    - name: Log version of script on client
      community.general.syslogger:
        ident: "lastminute"
        msg: "Finished {{ version }}"
        priority: "notice"
