---
- hosts: all
  tasks:
     - name: Pre-generate the kernel flags for ansible usage
       set_fact:
         procline: "quiet ipv6.disable=1 cgroup_enable=memory swapaccount=1"
    - name: Ensure /etc/default/grub has proper GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ procline }}\""
        owner: root
        group: root
        mode: '0644'
      notify:
        -  update grub
        -  reboot
    - name: Ensure /etc/default/grub has proper GRUB_TIMEOUT
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: "GRUB_TIMEOUT=.*"
        replace: "GRUB_TIMEOUT=3"
        owner: root
        group: root
        mode: '0644'
      notify:
        -  update grub
  handlers:
    - name: update grub
      command: /usr/sbin/update-grub
    - name: reboot
      reboot:
  roles:
    - role: stuvusIT.systemd-timesyncd
      timesync_timezone: "{{ timezone }}"
      timesync_ntp_hosts:
         - "{{ baseip }}.208"
         - "{{ baseip }}.209"
         - "{{ baseip }}.210"
      timesync_fallback_ntp_hosts:
        - "{{ baseip }}.208"
        - "{{ baseip }}.209"
        - "{{ baseip }}.210"
      tags: systemd-timesyncd
- hosts: contestants
  roles:
    - role: cups
    - role: ldapclient
      tags: ldapclient
      when: ldap_domain is defined
- hosts: ldapserver
  roles:
    - role: ldapserver
      tags: ldapserver
- hosts: all:!backup
  tasks:
    - name: point rsyslog to backup
      ansible.builtin.copy:
        content: |
          # ship the important logs to backup
          kern.warning                    @backup
          auth,authpriv.*                 @backup
        dest: /etc/rsyslog.d/70-clients.conf
        owner: root
        group: root
        mode: '0644'
- hosts: all
  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
        autoremove: yes
    - name: Ensure scoreboard in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.208	scoreboard"
        owner: root
        group: root
        mode: '0644'
    - name: Ensure packages in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.209	packages"
        owner: root
        group: root
        mode: '0644'
    - name: Ensure backup in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.210	backup"
        owner: root
        group: root
        mode: '0644'
    - name: Ensure printsrv in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.211	printsrv"
        owner: root
        group: root
        mode: '0644'
    - name: Replace sysopspackages.icpc.global with packages
      ansible.builtin.replace:
        path: /etc/apt/{{ item }}
        regexp: "sysopspackages.icpc.global"
        replace: "packages"
        owner: root
        group: root
        mode: '0644'
      loop:
        - "sources.list"
        - "sources.list.d/mono.list"
        - "sources.list.d/pypy-ubuntu-ppa-buster.list"
    - name: Log version of script on client
      community.general.syslogger:
        ident: "lastminute"
        msg: "Finished {{ version }}"
        priority: "notice"
      changed_when: false
