---
- hosts: all
  roles:
    - role: timezone
      tags: timezone
- hosts: contestants
  vars:
    baseip: 10.3.3
  roles:
    - role: ldapclient
      tags: ldapclient
    # - role: packages
    #   tags: packages
- hosts: ldapserver
  roles:
    - role: ldapserver
      tags: ldapserver
- hosts: all
  tasks:
    - name: Log version of script on client
      community.general.syslogger:
        ident: "lastminute"
        msg: "Finished {{ version }}"
        priority: "notice"
      changed_when: false
