---
- hosts: all
  roles:
    - role: stuvusIT.systemd-timesyncd
      timesync_timezone: "{{ timezone }}"
      timesync_ntp_hosts:
         - "{{ baseip }}.208"
         - "{{ baseip }}.209"
         - "{{ baseip }}.210"
      timesync_fallback_ntp_hosts:
        - "{{ baseip }}.208"
        - "{{ baseip }}.209"
        - "{{ baseip }}.210"
      tags: systemd-timesyncd
- hosts: contestants
  roles:
    - role: ldapclient
      tags: ldapclient
    # - role: packages
    #   tags: packages
- hosts: ldapserver
  roles:
    - role: ldapserver
      tags: ldapserver
- hosts: all
  tasks:
    - name: Log version of script on client
      community.general.syslogger:
        ident: "lastminute"
        msg: "Finished {{ version }}"
        priority: "notice"
      changed_when: false
