---
- hosts: all
  roles:
    - role: stuvusIT.systemd-timesyncd
      timesync_timezone: "{{ timezone }}"
      timesync_ntp_hosts:
         - "{{ baseip }}.208"
         - "{{ baseip }}.209"
         - "{{ baseip }}.210"
      timesync_fallback_ntp_hosts:
        - "{{ baseip }}.208"
        - "{{ baseip }}.209"
        - "{{ baseip }}.210"
      tags: systemd-timesyncd
- hosts: contestants
  roles:
    - role: ldapclient
      tags: ldapclient
    # - role: packages
    #   tags: packages
- hosts: ldapserver
  roles:
    - role: ldapserver
      tags: ldapserver
- hosts: all
  tasks:
    - name: Ensure scoreboard in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.208	scoreboard"
        owner: root
        group: root
        mode: '0644'
    - name: Ensure packages in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.209	packages"
        owner: root
        group: root
        mode: '0644'
    - name: Ensure backup in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ baseip }}.210	backup"
        owner: root
        group: root
        mode: '0644'
    - name: Log version of script on client
      community.general.syslogger:
        ident: "lastminute"
        msg: "Finished {{ version }}"
        priority: "notice"
      changed_when: false
