---
- name: Updates the users on the named hosts with locked passwords
  gather_facts: false
  hosts: contestants

  tasks:
    - name: Ensure and lock the user
      ansible.builtin.user:
        name: "{{ inventory_hostname }}"
        password: "*LOCKD*"
        shell: /bin/bash
        groups: teams
