# from galaxy
collections:
 - name: ansible.windows
 - name: chocolatey.chocolatey
 - name: community.general
 - name: community.windows
 - name: community.crypto

roles:
 - src: stuvusIT.systemd-timesyncd
