---
- name: Playbook to enable autologin
  hosts: contestants
  gather_facts: false
  roles:
    - role: v100

  tasks:
    - name: Stop vlc-webcam (to avoid conflicts)
      ansible.builtin.systemd:
        name: vlc-webcam
        state: stopped

    - name: Enable autologin to user v
      ansible.builtin.copy:
        content: |
          [SeatDefaults]
          # Autologin
          autologin-user=v
          autologin-timeout=0
        dest: /etc/lightdm/lightdm.conf.d/p100.conf
        owner: root
        group: root
        mode: '0644'

    - name: Check if v is currently running
      ansible.builtin.command: pgrep --uid v
      register: v_running
      ignore_errors: true
      changed_when: false

    - name: Restart lightdm
      ansible.builtin.systemd:
        name: lightdm
        state: restarted
