- name: Turboboost status
  hosts: contestants
  gather_facts: false
  tasks:
    - name: Check systemctl status turboboost_ht
      ansible.builtin.command: cat /proc/cpuinfo
      register: turboboost_ht
      changed_when: false

    - name: Print oldput from systemctl status
      ansible.builtin.debug:
        var: turboboost_ht.stdout_lines
