---
- name: Checking to see if vlc-webcam is running
  hosts: contestants
  gather_facts: false
  tasks:
    - name: Ensure vlc-webcam is running
      ansible.builtin.service:
        name: vlc-webcam
        state: started
