---
# on windows boxes
# set password on account (if none set)
#   (CTRL-ALT-DELETE, change password)
# run:
# elavated powershell
# bootstrap_windows.ps1
# on unix side:
# ansible-playbook --limit ballonprinter1 --extra-vars ansible_user=windows_user -e ansible_password=windows_password windows_lastminute.yml
# Also need (or put in inventory.yml): -e ansible_connection=winrm -e ansible_winrm_scheme=http -e ansible_winrm_transport=basic -e ansible_port=5985
# this was done to group_vars/windows.yml

- name: Windows hosts
  hosts: windows
  gather_facts: false
  roles:
    - role: windows

- name: Resolver hosts
  hosts: win_resolvers
  gather_facts: false
  roles:
    - role: resolver

- name: Presentation hosts
  hosts: presentation_clients
  gather_facts: false
  roles:
    - role: presclient

- name: Presentation admin hosts
  hosts: presentation_admins
  gather_facts: false
  roles:
    - role: presadmin

- name: Windows coachview hosts
  hosts: win_coachviews
  gather_facts: false
  tasks:
    - name: Import roles
      ansible.builtin.import_role:
        name: coachview
        tasks_from: windows.yml
      when: false

- name: Balloon printer hosts
  hosts: win_balloonprinters
  gather_facts: true
  roles:
    - role: balloonprinter
