---
- name: Check if the latest submit is available
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/files/submit"
  register: submit

- name: Download latest version
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/DOMjudge/domjudge/main/submit/submit
    dest: "{{ role_path }}/files/submit"
    mode: '0755'
  when: internet and submit.stat.islnk is not defined

- name: Install submit client
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/submit
    owner: root
    group: root
    mode: '0555'
    # only install this file once (otherwise updating the baseurl in it causes it to change every time)
    force: false
  with_first_found:
    - submit
    - /root/git/domjudge/submit/submit

- name: Add correct base URL
  ansible.builtin.lineinfile:
    path: /usr/local/bin/submit
    regexp: "^baseurl.*"
    line: 'baseurl = "{{ browser_urls | default(["https://domjudge"]) | first }}"'

- name: Add correct path to python3
  ansible.builtin.lineinfile:
    path: /usr/local/bin/submit
    regexp: "^#!/usr/bin/env python3$"
    line: "#!/usr/bin/python3"

- name: Is contest_detail TeamGuide.pdf available?
  delegate_to: localhost
  ansible.builtin.stat:
    path: "files/{{ contest_detail }}-domjudge-team-manual.pdf"
  register: domjudge_team_manual

- name: Copy domjudge TeamGuide.pdf (if ccs == domjudge)
  ansible.builtin.copy:
    src: "files/{{ contest_detail }}-domjudge-team-manual.pdf"
    dest: /usr/share/doc/icpc/TeamGuide.pdf
    mode: '0644'
  when: domjudge_team_manual.stat.exists

- name: Remove bad domjudge /etc/hosts entries (from imaging)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regex: "^.*domjudge$"
    state: absent
  when: enable_reverseproxy is not defined or not enable_reverseproxy

- name: Add domjudge to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ baseip }}.{{ domjudge_ip }}   domjudge # ANSIBLE MANAGED" # noqa: no-tabs
    owner: root
    group: root
    mode: '0644'
  when: enable_reverseproxy is not defined or not enable_reverseproxy

- name: Add domjudge doc dir
  ansible.builtin.file:
    path: /usr/share/apps/domjudge
    state: directory
    mode: '0755'

- name: Add domjudge png
  ansible.builtin.copy:
    src: files/DOMjudgelogo.png
    dest: /usr/share/apps/domjudge/DOMjudgelogo.png
    mode: '0644'

- name: Add domjudge desktop entry
  ansible.builtin.copy:
    src: files/domjudge.desktop
    dest: /usr/share/applications/ccs.desktop
    mode: '0644'
