- name: Systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

# - name: NTP
#   ansible.builtin.service:
#     name: ntp
#     state: restarted

- name: Rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Logrotate
  ansible.builtin.service:
    name: logrotate
    state: restarted

- name: IptablesLoad
  ansible.builtin.command: /etc/network/if-pre-up.d/iptablesload
  changed_when: false

- name: Backup_watchdog
  ansible.builtin.service:
    name: backup_watchdog
    state: restarted
