---
- name: Update hosts file so we talk to the proxyserver instead of the real server
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ baseip }}.205	{{ item }}" # noqa: no-tabs
    owner: root
    group: root
    mode: '0644'
  loop: "{{ reverseproxy_sites.keys() }}"
