---
- name: Server configuration
  ansible.builtin.include_tasks: server.yml
  when: reverseproxy_server

- name: Client configuration
  ansible.builtin.include_tasks: client.yml
  when: not reverseproxy_server
