---
- name: install nginx
  ansible.builtin.apt: pkg=nginx state=present

- name: remove default nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: install the ssl key
  ansible.builtin.copy:
    content: "{{ reverseproxy_key }}"
    dest: /etc/ssl/reverseproxy.key
    mode: 0600

- name: install the ssl certificate
  ansible.builtin.copy:
    content: "{{ reverseproxy_cert }}"
    dest: /etc/ssl/reverseproxy.cert
    mode: 0644

- name: install our kattis reverse proxy config
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/reverseproxy.conf
    mode: 0644
    owner: root
    group: root
    lstrip_blocks: true
    trim_blocks: true
  notify: reload nginx

- name: enable the reverseproxy nginx config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/reverseproxy.conf
    dest: /etc/nginx/sites-enabled/reverseproxy
    state: link
  notify: reload nginx
