{
 "title": "Sysops Core Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Sysops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core Service Ping",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"cds|backup|printsrv|packages|reverseproxy\"}",
     "legendFormat": "{{instance}}"
    },
    { "expr": "cups_up", "legendFormat": "cups service (on printsrv)" }
   ]
  },
  {
   "title": "Systems Load",
   "type": "timeseries",
   "description": "Load Average 1 minute",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "node_load1{job=\"systems\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Team Systems Load",
   "type": "timeseries",
   "description": "Load Average 1 minute",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_teams\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CDS Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"cds\",job=\"systems\",state=\"active\",name=~\"(cds|p100|live).service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Printing Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 11 },
   "targets": [
    { "expr": "cups_print_jobs_total", "legendFormat": "Total Jobs" },
    { "expr": "cups_print_jobs_active", "legendFormat": "Pending Jobs" }
   ]
  },
  {
   "title": "Node Exporter Status",
   "type": "state-timeline",
   "description": "Whether node_exporter is alive or not",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "up{job=~\"node_teams|systems\"} != 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recently Rebooted Team Machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_teams\"} - node_boot_time_seconds{job=\"node_teams\"} < 1800",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Systems Net Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"systems\",device!=\"wlo1\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} recv {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"systems\",device!=\"wlo1\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} trans {{ device }}"
    }
   ]
  },
  {
   "title": "Team System Uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_teams\"} - node_boot_time_seconds{job=\"node_teams\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Disk <100GiB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint!=\"/boot/efi\"} < (100*1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ICPC Live Related Things", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "VLC Webcam Service Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node_teams\",name=\"vlc-webcam.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VLC Screen Service Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node_teams\",name=\"vlc-screen.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Time Drift",
   "type": "timeseries",
   "description": "This is the time difference from the backup host (ish)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "timestamp(node_time_seconds) - node_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Syncronized Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds{job=\"node_teams\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}