{
 "title": "Sysops Core Dashboard Editable",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Sysops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core Service Ping",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"cds|backup|printsrv|packages|reverseproxy\"}",
     "legendFormat": "{{instance}}"
    },
    { "expr": "cups_up", "legendFormat": "cups service (on printsrv)" }
   ]
  },
  {
   "title": "Disk free < 250GB",
   "type": "timeseries",
   "description": "Disk free less than 250 GB",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint!=\"/boot/efi\"} < 1024*1024*1024*250",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Systems Load",
   "type": "timeseries",
   "description": "Load Average 1 minute",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "node_load1{job=\"systems\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Recently Rebooted Team Machines",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_teams\"} - node_boot_time_seconds{job=\"node_teams\"} < 1800",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CDS Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"cds\",job=\"systems\",state=\"active\",name=~\"(cds|p100|live).service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power supply unplugged",
   "type": "state-timeline",
   "description": "Shows hosts that are not plugged in",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "node_power_supply_online{power_supply=\"ADP1\"} != 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Machine metrics unreachable",
   "type": "state-timeline",
   "description": "Whether node_exporter is alive or not",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "up{job=~\"node_teams|systems\"} != 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperatures above 80c",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius > 80",
     "legendFormat": "{{instance}}-{{chip}}-{{sensor}}"
    }
   ]
  },
  {
   "title": "Team Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node_teams\"} == 1)",
     "legendFormat": "Online"
    },
    {
     "expr": "count(up{job=\"node_teams\"} == 0)",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Team Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox\",instance=~\"team.*\"} == 1)",
     "legendFormat": "Online"
    },
    {
     "expr": "count(probe_success{job=\"blackbox\",instance=~\"team.*\"} == 0)",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Printing Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "cups_print_jobs_total", "legendFormat": "Total Jobs" },
    { "expr": "cups_print_jobs_active", "legendFormat": "Pending Jobs" }
   ]
  },
  {
   "title": "Systems Net Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"systems\",device!=\"wlo1\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} recv {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"systems\",device!=\"wlo1\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} trans {{ device }}"
    }
   ]
  },
  {
   "title": "Team Systems Load (>3.5)",
   "type": "timeseries",
   "description": "Load Average 1 minute",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_teams\"} > 3.5",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Team System Uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_teams\"} - node_boot_time_seconds{job=\"node_teams\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "ICPC Live Related Things", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "VLC Webcam Service Status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node_teams\",name=\"vlc-webcam.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VLC Screen Service Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{job=\"node_teams\",name=\"vlc-screen.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Time Drift",
   "type": "timeseries",
   "description": "This is the time difference from the backup host (ish)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "timestamp(node_time_seconds) - node_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Syncronized Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds{job=\"node_teams\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}