---
- name: Stop any running presentation clients and delete the old copy
  ansible.windows.win_shell: |
    Stop-Process -name "java"
    Start-Sleep -seconds 1
    Remove-Item -recurse -force /users/{{ ansible_user }}/Desktop/presclient

- name: Fetch presentation client
  ansible.windows.win_copy:
    src: files/presentations-{{ presclient_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip

- name: Unzip presentation client
  community.windows.win_unzip:
    src: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/presclient
    remote_src: true
    creates: /Users/{{ ansible_user }}/Desktop/presclient
