---
- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk11jre
    state: present
  when: not skip_chocolatey

- name: Update/download and install the presentation client
  block:
    - name: Get prerelease version
      delegate_to: 127.0.0.1
      ansible.builtin.uri:
        url: https://api.github.com/repos/icpctools/icpctools/releases?per_page=3
        headers: "{{ github_headers }}"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: latest_presentation_release_array
      when: presclient_version is not defined

    - name: Set presentation client latest version
      ansible.builtin.set_fact:
        presclient_version: "{{ latest_presentation_release_array.json[0].name | replace('v', '') }}"
      when: presclient_version is not defined

    - name: Download presentation client
      ansible.windows.win_get_url:
        url: https://github.com/icpctools/icpctools/releases/download/v{{ presclient_version }}/presentations-{{ presclient_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip

    - name: Stop the existing presentation client
      ansible.windows.win_shell: stop-process -name "java" -force
      failed_when: false # we don't care if this fails

    - name: Delete existing folder
      ansible.windows.win_file:
        path: /Users/{{ ansible_user }}/Desktop/presclient
        state: absent

    - name: Unzip presentation client
      community.windows.win_unzip:
        src: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/presclient
        remote_src: true
        creates: /Users/{{ ansible_user }}/Desktop/presclient

# yamllint disable rule:line-length
- name: Add bat script to launch the presentation client
  ansible.windows.win_copy:
    content: |
      REM set ICPC_BRANDING_PRES=org.icpc.tools.presentation.contest.internal.presentations.BrandingPresentation
      c:/users/{{ ansible_user }}/desktop/presclient/client.bat {{ presclient_cds_url }} {{ presclient_user }} {{ presclient_pass }} --name {{ presclient_name | default(inventory_hostname) }}
    dest: /users/{{ ansible_user }}/desktop/launch_pres_client.bat
# yammlint enable rule:line-length

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/presclient/client.bat"
    dest: "c:/Users/{{ ansible_user }}/Desktop/presclient.lnk"
    arguments: '{{ presclient_cds_url }} {{ presclient_user }} {{ presclient_pass }} --name "{{ presclient_name | default(inventory_hostname) }}"'

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/presclient.lnk"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/presclient.lnk"
