# windows updates

- name: Set autologin
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    type: "{{ item.type }}"
  loop:
    - { name: DefaultUserName, value: "{{ ansible_user }}", type: string }
    - { name: DefaultPassword, value: "{{ ansible_password }}", type: string } # TODO: mask this out of the ansible output
    - { name: AutoAdminLogon, value: 1, type: dword }

- name: Disable lid/power button/sleep button actions
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Power\PowerSettings\{{ item.key }}
    name: "{{ item.name }}"
    data: "{{ item.value }}"
    type: "{{ item.type }}"
  loop:
    # Power button action
    - { key: "7648EFA3-DD9C-4E3E-B566-50F929386280", name: "DCSettingIndex", value: 0, type: "dword"}
    - { key: "7648EFA3-DD9C-4E3E-B566-50F929386280", name: "ACSettingIndex", value: 0, type: "dword"}
    # Lid Switch action
    - { key: "5CA83367-6E45-459F-A27B-476B1D01C936", name: "DCSettingIndex", value: 0, type: "dword"}
    - { key: "5CA83367-6E45-459F-A27B-476B1D01C936", name: "ACSettingIndex", value: 0, type: "dword"}
    # Sleep button action
    - { key: "96996BC0-AD50-47EC-923B-6F41874DD9EB", name: "DCSettingIndex", value: 0, type: "dword"}
    - { key: "96996BC0-AD50-47EC-923B-6F41874DD9EB", name: "ACSettingIndex", value: 0, type: "dword"}


- name: Disable windows updates
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    type: dword
    data: 1

- name: Turn off screen sleep/disk sleep while on AC
  ansible.windows.win_command: powercfg -setacvalueindex scheme_balanced {{ item }} 0
  loop:
    - sub_video videoidle
    - sub_disk diskidle
    - sub_sleep standbyidle

- name: Turn off screen sleep/disk sleep while on DC/Battery
  ansible.windows.win_command: powercfg -setdcvalueindex scheme_balanced {{ item }} 0
  loop:
    - sub_video videoidle
    - sub_disk diskidle
    - sub_sleep standbyidle

- name: Set the power plan to balanced (which is what we changed settings for)
  community.windows.win_power_plan:
    name: balanced

- name: Force 96dpi to LogPixels (i.e. 100% scaling)
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: LogPixels
    type: dword
    data: 96

- name: Force 96dpi to Win8DpiScaling (i.e. 100% scaling)
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: Win8DpiScaling
    type: dword
    data: 1

- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk11jre
    state: present

- name: Update/download and install the presentation client
  block:
    - name: Get prerelease version
      delegate_to: 127.0.0.1
      ansible.builtin.uri:
        url: https://api.github.com/repos/icpctools/icpctools/releases?per_page=3
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: latest_presentation_release_array
      when: presclient_version is not defined

    - name: Set presentation client latest version
      ansible.builtin.set_fact:
        presclient_version: "{{ latest_presentation_release_array.json[0].name | replace('v', '') }}"
      when: presclient_version is not defined

    - name: Download presentation client
      ansible.windows.win_get_url:
        url: https://github.com/icpctools/icpctools/releases/download/v{{ presclient_version }}/presentations-{{ presclient_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip

    - name: Unzip presentation client
      community.windows.win_unzip:
        src: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/presclient
        remote_src: true


- name: Add bat script to launch the presentation client
  ansible.windows.win_copy:
    content: |
      c:/Users/{{ ansible_user }}/Desktop/presclient/client.bat {{ presclient_cds_url }} {{ presclient_user }} {{ presclient_pass }} --name {{ inventory_hostname }} # noqa: yaml[line-length]
    dest: /Users/{{ ansible_user }}/Desktop/launch_pres_client.bat

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/presclient/client.bat"
    dest: "c:/Users/{{ ansible_user }}/Desktop/presclient.lnk"
    arguments: "{{ presclient_cds_url }} {{ presclient_user }} {{ presclient_pass }} --name {{ inventory_hostname }}"

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/presclient.lnk"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/presclient.lnk"

