---
- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk
    version: 21.0.0
    state: present
  when: not skip_chocolatey

- name: Download presentation zip
  github_release:
    repo: icpctools/icpctools
    asset: "^presentations-.*\\.zip$"
    version: "{{ presclient_version }}"
    dest: files/presentations.zip
  delegate_to: localhost

- name: Download presentation client
  ansible.windows.win_copy:
    src: files/presentations.zip
    dest: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip

- name: Stop the existing presentation client
  ansible.windows.win_shell: stop-process -name "java" -force
  failed_when: false # we don't care if this fails

- name: Delete existing folder
  ansible.windows.win_file:
    path: /Users/{{ ansible_user }}/Desktop/presclient
    state: absent

- name: Unzip presentation client
  community.windows.win_unzip:
    src: /Users/{{ ansible_user }}/Desktop/presentations-{{ presclient_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/presclient
    remote_src: true
    creates: /Users/{{ ansible_user }}/Desktop/presclient

# yamllint disable rule:line-length
- name: Add bat script to launch the presentation client
  ansible.windows.win_copy:
    content: |
      REM set ICPC_BRANDING_PRES=org.icpc.tools.presentation.contest.internal.presentations.BrandingPresentation
      c:/users/{{ ansible_user }}/desktop/presclient/client.bat {{ presclient_cds_url }} {{ presclient_user }} {{ presclient_pass }} --name {{ presclient_name | default(inventory_hostname) }}
    dest: /users/{{ ansible_user }}/desktop/launch_pres_client.bat
# yammlint enable rule:line-length

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/presclient/client.bat"
    dest: "c:/Users/{{ ansible_user }}/Desktop/presclient.lnk"
    arguments: '{{ presclient_cds_url }} {{ presclient_user }} {{ presclient_pass }} --name "{{ presclient_name | default(inventory_hostname) }}"'

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/presclient.lnk"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/presclient.lnk"
