---
- name: Reload nginx
  ansible.builtin.service:
    name: Reload nginx
    state: reloaded

- name: Systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: IptablesLoad
  ansible.builtin.command: /etc/network/if-pre-up.d/iptablesload
  changed_when: false
