---
- name: Install a new cupsd.conf file
  ansible.builtin.copy:
    src: files/cupsd.conf
    dest: /etc/cups/cupsd.conf
    mode: "0644"
    owner: root
    group: root

- name: Install packages needed to munging pdfs
  ansible.builtin.package:
    name:
      - imagemagick
      - pdftk

- name: Listen on all ports for cupsd.conf
  ansible.builtin.lineinfile:
    path: /etc/cups/cupsd.conf
    regexp: 'Listen localhost:631'
    line: 'Listen *:631'
  notify: Restart cups

- name: Add ServerAlias to cupsd.conf
  ansible.builtin.lineinfile:
    path: /etc/cups/cupsd.conf
    line: 'ServerAlias *'
  notify: Restart cups

- name: Remove old policy from ImagicMagick
  ansible.builtin.lineinfile:
    path: /etc/ImageMagick-6/policy.xml
    state: absent
    regexp: '<policy domain="coder" rights="none" pattern="{{ item }}" />'
  loop:
    - PS
    - PS2
    - PS3
    - EPS
    - PDF
    - XPS

- name: Installing banner page empty template
  ansible.builtin.copy:
    src: files/{{ contest }}-banner-template.pdf
    dest: /usr/share/cups/data/banner-template.pdf
    mode: '0644'

- name: Check if the class exists
  ansible.builtin.command: lpstat -c contest
  register: lpstat_contest
  changed_when: false
  ignore_errors: true


- name: Install pre-reqs for cups_exporter (from ThoreKr/cups_exporter)
  ansible.builtin.apt:
    pkg:
      - python3-cups
      - python3-prometheus-client

- name: Install cups_exporter
  ansible.builtin.copy:
    src: cups_exporter.py
    dest: /usr/local/bin/cups_exporter.py
    mode: "0755"

- name: Increase nofile ulimits
  ansible.builtin.copy:
    content: |
      root        hard nofile 4096
      root        soft nofile 2048
    dest: /etc/security/limits.d/printsrv.conf
    owner: root
    mode: '0644'

- name: Setup cups_exporter as a systemd service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=cups-exporter exports prometheus metrics for cups printers
      After=network.target multi-user.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/cups_exporter.py
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/cups-exporter.service
    owner: root
    mode: '0644'

- name: Enable/start cups_exporter
  ansible.builtin.service:
    name: cups-exporter
    enabled: true
    state: started
    daemon_reload: true

# may need two icpc-banners one for letter, one for a4
- name: Add icpc-banner filter
  ansible.builtin.copy:
    src: files/icpc-banner
    dest: /usr/lib/cups/filter/icpc-banner
    owner: root
    group: root
    mode: '0755'

- name: Configure printers
  ansible.builtin.include_tasks: printer.yml
  vars:
    printer: "{{ item.name }}"
    printer_uri: "{{ item.uri | default('ipp://' + item.name) }}"
    model: "{{ item.model | default('everywhere') }}"
    is_default: "{{ item.is_default | default(false) }}"
    contestprinter: "{{ item.contestprinter | default(false) }}"
  loop: "{{ printserver_print_config }}"


- name: Create the directories for our metadata
  ansible.builtin.file:
    state: directory
    path: /usr/share/cups/data/{{ item }}
    mode: '0755'
  loop:
    - UniversityNames
    - Pictures
    - Logos

- name: Create university information for team
  ansible.builtin.copy:
    content: "{{ item.display_name }}"
    dest: /usr/share/cups/data/UniversityNames/team{{ item.id }}.txt
    mode: '0644'
  loop: "{{ lookup('file', '/root/contest_repo/contests/' + printsrv_contest_id + '/teams.json') | from_json }}"

- name: Copy logos
  ansible.builtin.copy:
    src: "/root/contest_repo/contests/{{ printsrv_contest_id }}/organizations/{{ item.organization_id }}/logo.png"
    dest: /usr/share/cups/data/Logos/team{{ item.id }}.png
    mode: '0644'
  loop: "{{ lookup('file', '/root/contest_repo/contests/' + printsrv_contest_id + '/teams.json') | from_json }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy team pictures
  ansible.builtin.copy:
    src: "/root/contest_repo/contests/{{ printsrv_contest_id }}/teams/{{ item.id }}/photo.jpg"
    dest: /usr/share/cups/data/Pictures/team{{ item.id }}.jpg
    mode: '0644'
  loop: "{{ lookup('file', '/root/contest_repo/contests/' + printsrv_contest_id + '/teams.json') | from_json }}"
  ignore_errors: "{{ ansible_check_mode }}"
