---
- name: Install a new cupsd.conf file
  ansible.builtin.copy:
    src: files/cupsd.conf
    dest: /etc/cups/cupsd.conf
    mode: "0644"
    owner: root
    group: root

- name: Add printers to /etc/hosts
  ansible.builtin.lineinfile:
    state: present
    line: "{{ item.ip }} {{ item.name }}"
    path: /etc/hosts
  loop:
    - {ip: 10.4.4.200, name: balloonprinter}
    - {ip: 10.4.4.201, name: teamprint1}
    - {ip: 10.4.4.202, name: teamprint2}
    - {ip: 10.4.4.203, name: teamprint3}
    - {ip: 10.4.4.204, name: judgeprinter}
    - {ip: 10.4.4.205, name: systemsprinter}

- name: Install packages needed to munging pdfs
  ansible.builtin.package:
    name:
      - imagemagick
      - pdftk

- name: Listen on all ports for cupsd.conf
  ansible.builtin.lineinfile:
    path: /etc/cups/cupsd.conf
    regexp: 'Listen localhost:631'
    line: 'Listen *:631'
  notify: Restart cups

- name: Remove old policy from ImagicMagick
  ansible.builtin.lineinfile:
    path: /etc/ImageMagick-6/policy.xml
    state: absent
    regexp: '<policy domain="coder" rights="none" pattern="{{ item }}" />'
  loop:
    - PS
    - PS2
    - PS3
    - EPS
    - PDF
    - XPS

- name: Installing banner page empty template
  ansible.builtin.copy:
    src: files/{{ contest }}-banner-template.pdf
    dest: /usr/share/cups/data/banner-template.pdf
    mode: '0644'

- name: Check if the class exists
  ansible.builtin.command: lpstat -c contest
  register: lpstat_contest
  changed_when: false
  ignore_errors: true


- name: Install pre-reqs for cups_exporter (from ThoreKr/cups_exporter)
  ansible.builtin.apt:
    pkg:
      - python3-cups
      - python3-prometheus-client

- name: Install cups_exporter
  ansible.builtin.copy:
    src: cups_exporter.py
    dest: /usr/local/bin/cups_exporter.py
    mode: "0755"

- name: Increase nofile ulimits
  ansible.builtin.copy:
    content: |
      root        hard nofile 4096
      root        soft nofile 2048
    dest: /etc/security/limits.d/printsrv.conf
    owner: root
    mode: '0644'

- name: Setup cups_exporter as a systemd service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=cups-exporter exports prometheus metrics for cups printers
      After=network.target multi-user.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/cups_exporter.py
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/cups-exporter.service
    owner: root
    mode: '0644'

- name: Enable/start cups_exporter
  ansible.builtin.service:
    name: cups-exporter
    enabled: true
    state: started
    daemon_reload: true

# may need two icpc-banners one for letter, one for a4
- name: Add icpc-banner filter
  ansible.builtin.copy:
    src: files/icpc-banner
    dest: /usr/lib/cups/filter/icpc-banner
    owner: root
    group: root
    mode: '0755'

- name: Configure printers
  ansible.builtin.include_tasks: printer.yml
  vars:
    printer: "{{ item.name }}"
    is_default: "{{ item.is_default | default(false) }}"
    contestprinter: "{{ item.contestprinter | default(false) }}"
  loop: "{{ printserver_print_config }}"


# TODO: add the university names+logos, and team photos
# They go in files like this, with names based on
# /usr/share/cups/data/UniversityNames/$user.txt
# /usr/share/cups/data/Pictures/$user.png
# /usr/share/cups/data/Logos/$user.png
#
#
