---

- name: Install requirements
  ansible.builtin.apt:
    pkg:
      - xfce4
      - xfce4-goodies
      - xrdp

- name: Update startwm.sh
  ansible.builtin.copy:
    src: files/startwm.sh
    dest: /etc/xrdp/startwm.sh
    mode: '0755'

- name: Add judge user
  ansible.builtin.user:
    name: judge
    group: judges
    password: "{{ judge_password }}"
