---
vlc_webcam_cpu_affinity: 8,10
vlc_screen_cpu_affinity: 6
vlc_alsa_device: 'hw:0,0' # run arecord -L to determine this
vlc_webcam_device: video2 # ls /dev/video*, maybe run ffplay /dev/videoN to preview it to find the right camera
vlc_webcam_channels: 1 # How many audio channels to record from. Webcams are probably mono?
