---
- name: Check for not windows, include linux.yml
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != 'Windows'
- name: Check for windows, include windows.yml
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
