- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk11jre
    state: present

- name: Download balloon client
  ansible.windows.win_get_url:
    url: https://github.com/icpctools/icpctools/releases/download/v{{ balloon_version }}/balloonUtil-{{ balloon_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/balloonUtil-{{ balloon_version }}.zip

- name: Unzip balloon client
  community.windows.win_unzip:
    src: /Users/{{ ansible_user }}/Desktop/balloonUtil-{{ balloon_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/balloon
    remote_src: true

- name: Copy a shortcut to launch the balloon client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/balloon/balloon.bat"
    dest: "c:/Users/{{ ansible_user }}/Desktop/balloon.lnk"
    arguments: "{{ balloon_cds_url }} {{ balloon_user }} {{ balloon_pass }}"

- name: Copy a shortcut to launch the balloon client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/balloon.lnk"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/balloon.lnk"
