- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk
    version: 21.0.0
    state: present
  when: not skip_chocolatey

- name: Fetch balloonutil
  ansible.windows.win_copy:
    src: files/balloonUtil-{{ balloon_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/balloonUtil-{{ balloon_version }}.zip

- name: Unzip balloonutil
  community.windows.win_unzip:
    src: /Users/{{ ansible_user }}/Desktop/balloonUtil-{{ balloon_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/balloon
    remote_src: true
    creates: /Users/{{ ansible_user }}/Desktop/balloon

- name: Copy a shortcut to launch the balloon client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/balloon/balloon.bat"
    dest: "c:/Users/{{ ansible_user }}/Desktop/balloon.lnk"
    arguments: "{{ balloon_cds_url }} {{ balloon_user }} {{ balloon_pass }}"

- name: Copy a shortcut to launch the balloon client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/balloon.lnk"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/balloon.lnk"
