- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk11jre
    state: present

- name: Update/download and install the resolver client
  block:
    - name: Get prerelease version
      delegate_to: 127.0.0.1
      ansible.builtin.uri:
        url: https://api.github.com/repos/icpctools/icpctools/releases?per_page=3
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: latest_resolver_release_array
      when: internet and resolver_version is not defined

    - name: Set resolver client latest version
      ansible.builtin.set_fact:
        resolver_version: "{{ latest_resolver_release_array.json[0].name | replace('v', '') }}"
      when: resolver_version is not defined

    - name: Download resolver client
      delegate_to: localhost
      ansible.builtin.get_url:
        url: https://github.com/icpctools/icpctools/releases/download/v{{ resolver_version }}/resolver-{{ resolver_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/resolver-{{ resolver_version }}.zip
        mode: '0644'
      when: internet

    - name: Copy the resolver
      win_copy:
        src: "{{ item }}"
        dest: "%TEMP%/resolver.zip"
      with_first_found:
        - files:
            - /tmp/resolver-{{ resolver_version }}.zip
            - files/resolver-{{ resolver_version }}.zip
    - name: Unpack the resolver
      community.windows.win_unzip:
        src: "%TEMP%/resolver.zip"
        dest: /Users/{{ ansible_user }}/Desktop/resolver
        creates: /Users/{{ ansible_user }}/Desktop/resolver

- name: Add bat script to launch the resolver client
  ansible.windows.win_copy:
    content: >
      c:/Users/{{ ansible_user }}/Desktop/resolver/resolver.bat
      {{ resolver_cds_url }}
      {{ resolver_user }} {{ resolver_pass }}
      --client
    dest: /Users/{{ ansible_user }}/Desktop/launch_resolver.bat

- name: Copy a shortcut to launch the resolver client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/resolver/resolver.bat"
    dest: "c:/Users/{{ ansible_user }}/Desktop/resolver.lnk"
    arguments: "{{ resolver_cds_url }} {{ resolver_user }} {{ resolver_pass }} --client"

- name: Copy a shortcut to launch the resolver client on startup
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/resolver.lnk"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/resolver.lnk"
