---
- name: Enable DNS bits in resolved.conf
  ansible.builtin.replace:
    path: /etc/systemd/resolved.conf
    regexp: '^[#]?DNS=.*'
    replace: 'DNS=8.8.8.8 1.1.1.1'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Systemd-resolved

# This seems to be part of icpc_host_backup?
# And also, aren't we using systemd-timesyncd
# - name: Update ntp.conf
#   ansible.builtin.copy:
#     src: ntp.conf.new
#     dest: /etc/ntp.conf
#     mode: '0644'
#   notify:
#     - NTP

- name: Update iptables.rules
  ansible.builtin.template:
    src: templates/iptables.rules.j2
    dest: /etc/iptables.rules
    mode: '0644'
  notify:
    - IptablesLoad

- name: Ensure required packages are installed
  ansible.builtin.apt:
    pkg:
      - apache2
      - iptables
      - bash
      - ssl-cert
      - ntp
      - awscli
    state: present

- name: Configure apache2
  block:
    - name: Install packages.pem
      ansible.builtin.copy:
        src: /root/ca/intermediate/certs/packages.cert.pem
        dest: /etc/ssl/certs/packages.pem
        mode: '0644'
      notify: Apache2

    - name: Install packages.key
      ansible.builtin.copy:
        src: /root/ca/intermediate/private/packages.key.pem
        dest: /etc/ssl/private/packages.key
        group: ssl-cert
        mode: '0640'
      notify: Apache2

    - name: Install sites-available/packages.conf
      ansible.builtin.copy:
        src: files/sites.packages.conf
        dest: /etc/apache2/sites-available/packages.conf
        mode: '0644'
      notify: Apache2

    - name: Install conf-available/packages.conf
      ansible.builtin.copy:
        src: files/conf.packages.conf
        dest: /etc/apache2/conf-available/packages.conf
        mode: '0644'
      notify: Apache2

    - name: Ensure we are not listening on port 80
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: "# Listen 80"
        owner: root
        group: root
        mode: '0644'
      notify: Apache2

    # creates symlinks in /etc/apache2/mods-enabled
    - name: Enable ssl mod
      ansible.builtin.file:
        dest: /etc/apache2/mods-enabled/{{ item }}
        src: /etc/apache2/mods-available/{{ item }}
        state: link
      with_items:
        - ssl.conf
        - ssl.load
        # Dependencies that need to be enabled for ssl to work
        - socache_shmcb.load
        # These are probably enabled by default, but might as well list them here too?
        - mime.conf
        - mime.load
        - setenvif.conf
        - setenvif.load

    - name: Enable packages site
      ansible.builtin.file:
        dest: /etc/apache2/sites-enabled/packages.conf
        src: /etc/apache2/sites-available/packages.conf
        state: link
      notify: Apache2

    - name: Enable packages conf
      ansible.builtin.file:
        dest: /etc/apache2/conf-enabled/packages.conf
        src: /etc/apache2/conf-available/packages.conf
        state: link
      notify: Apache2

    - name: Remove 000-default
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: Apache2
