---
- name: Enable DNS bits in resolved.conf
  ansible.builtin.replace:
    path: /etc/systemd/resolved.conf
    regexp: '^[#]?DNS=.*'
    replace: 'DNS=8.8.8.8 1.1.1.1'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Systemd-resolved

- name: Update iptables.rules
  ansible.builtin.template:
    src: templates/iptables.rules.j2
    dest: /etc/iptables.rules
    mode: '0644'
  notify:
    - IptablesLoad

- name: Install nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present
    policy_rc_d: 101 # prevent nginx from starting after installation

- name: Ensure required packages are installed
  ansible.builtin.apt:
    pkg:
      - iptables
      - bash
      - ssl-cert
    state: present

- name: Configure nginx for packages
  block:
    - name: Install packages.pem
      ansible.builtin.copy:
        src: /root/ca/intermediate/certs/packages{{ keyprefix || default("") }}.cert.pem
        dest: /etc/ssl/certs/packages.pem
        mode: '0644'
      notify: Reload nginx

    - name: Install packages.key
      ansible.builtin.copy:
        src: /root/ca/intermediate/private/packages{{ keyprefix || default("") }}.key.pem
        dest: /etc/ssl/private/packages.key
        group: ssl-cert
        mode: '0640'
      notify: Reload nginx

    - name: Install sites-available/packages.conf
      ansible.builtin.copy:
        src: files/nginx.packages.conf
        dest: /etc/nginx/sites-available/packages.conf
        mode: '0644'
      notify: Reload nginx

    - name: Link sites-available to sites-enabled
      ansible.builtin.file:
        dest: /etc/nginx/sites-enabled/packages.conf
        src: /etc/nginx/sites-available/packages.conf
        state: link
      notify: Reload nginx

    - name: Remove default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload nginx
