#!/usr/bin/python3

import yaml
import argparse

parser = argparse.ArgumentParser(description='script to build hosts.yml')
parser.add_argument('-w', action='store_true', dest='wf', help='enable world finals mode')
args = parser.parse_args()

contestants = {}
judges = {}
others = {}
if args.wf:
    name = "wf2024"
    detail = "2023Astana"
    timezone = "Africa/Cairo"
    max_team = 146
    max_human_judge = 14
    max_pc2_autojudge = 10
    max_kattis_autojudge = 0
    max_domjudge_autojudge = 12
    max_domjudge_ccsadmin = 4
    # pc2 for wf2023
    max_ccsadmin = 8
    papersize = "A4"
    enable_vlc = True
    ccs = "domjudge"
else:
    name = "nac2024"
    detail = "2024Florida"
    timezone = "America/New_York"
    max_team = 53
    max_human_judge = 12
    max_pc2_autojudge = 5
    max_kattis_autojudge = 0
    max_domjudge_autojudge = 5
    max_domjudge_ccsadmin = 0
    max_ccsadmin = 0
    papersize = "letter"
    enable_vlc = True
    ccs = "domjudge"


def print_host(num, hostname, ip, list_fh, group, base_ip=0):
    group[f"{hostname}{num}"] = {"ansible_host": f"{ip}.{base_ip+num}"}
    print(f"{hostname}{num}", file=list_fh)

def print_host_wf(base, num, hostname, ip, list_fh, group, base_ip=0):
    group[f"{hostname}{num}"] = {"ansible_host": f"{ip}.{base_ip+num-base}"}
    print(f"{hostname}{num}", file=list_fh)

def print_host_wf46(num, hostname, ip, list_fh, group, base_ip=0):
    print_host_wf(46000, num+46000, hostname, ip, list_fh, group, base_ip)

def print_host_wf47(num, hostname, ip, list_fh, group, base_ip=0):
    print_host_wf(47000, num+47000, hostname, ip, list_fh, group, base_ip)

def print_server(hostname, ip, group=[]):
    group[f"{hostname}"] = {"ansible_host": f"{ip}"}


if __name__ == "__main__":
    with open("../hosts.yml", "wt") as fh:
        with open("../list.team", "wt") as list_fh:
            # revert after wf2023
            if args.wf:
                for i in range(max_team):
                   print_host_wf46(i + 1, "team", "10.1.46", list_fh, contestants)
                for i in range(max_team):
                    print_host_wf47(i + 1, "team", "10.1.47", list_fh, contestants)
            else:
                for i in range(max_team):
                    print_host(i + 1, "team", "10.1.1", list_fh, contestants)
        document = f"""
contestants:
  hosts: {contestants}
"""
        print(yaml.dump(yaml.safe_load(document), explicit_start=True), file=fh)
        with open("../list.judge", "wt") as list_fh:
            for i in range(max_human_judge):
                print_host(i + 1, "judge", "10.2.2", list_fh, judges)
        with open("../list.autojudges", "wt") as list_fh:
            for i in range(max_kattis_autojudge):
                print_host(i + 1, "autojudge", "10.2.2", list_fh, judges, 31)
        with open("../list.pc2judges", "wt") as list_fh:
            for i in range(max_pc2_autojudge):
                print_host(i + 1, "pc2-aj", "10.2.2", list_fh, judges, 127)
        with open("../list.domjudges", "wt") as list_fh:
            for i in range(max_domjudge_autojudge):
                print_host(i + 1, "domjudge-judgehost", "10.2.2", list_fh, judges, 191)
        document = f"""
judges:
  hosts: {judges}
"""
        print(yaml.dump(yaml.safe_load(document), explicit_start=False), file=fh)
        with open("../list.domjudges_ccsadmin", "wt") as list_fh:
            for i in range(max_domjudge_ccsadmin):
                print_host(i + 1, "domjudge-ccsadmin", "10.3.3", list_fh, others, 223)
        with open("../list.ccsadmin", "wt") as list_fh:
            for i in range(max_ccsadmin):
                print_host(i + 1, "ccsadmin", "10.3.3", list_fh, others, 231)
        print_server("reverseproxy", "10.3.3.205", others)
        # print_server("media", "10.3.3.206", others);
        print_server("cds", "10.3.3.207", others)
        print_server("scoreboard", "10.3.3.208", others)
        print_server("packages", "10.3.3.209", others)
        print_server("backup", "10.3.3.210", others)
        print_server("printsrv", "10.3.3.211", others)
        print_server("balloonmanager", "10.4.4.149", others)
        # print_server("kattis", "10.3.3.212", others)
        # print_server("kattisbackup", "10.3.3.213", others)
        print_server("pc2-shadowccs", "10.3.3.214", others)
        # print_server("domjudge-shadowccs", "10.3.3.215", others)
        print_server("domserver", "10.3.3.216", others)
        document = f"""
others:
  hosts:
    {others}
"""
        print(yaml.dump(yaml.safe_load(document), explicit_start=False), file=fh)
        document_unused = f"""
ldapserver:
  hosts:
    ldap-server1:
      ansible_host: 10.3.3.211
    ldap-server2:
      ansible_host: 10.3.3.210
"""
        document = f"""
grafana:
  hosts:
    backup:
      ansible_host: 10.3.3.210
ntpservers:
  hosts:
     backup:
       ansible_host: 10.3.3.210
     scoreboard:
       ansible_host: 10.3.3.208
     packages:
       ansible_host: 10.3.3.209
all:
  vars:
    ccs: {ccs}
    timezone: {timezone}
    root_password:  null
    disable_sources_list_changes: false
    enable_reverseproxy: {not args.wf}
    contest:  {name}
    contest_detail: {detail}
    papersize:  {papersize}
    enable_vlc: {enable_vlc}

"""
        print(yaml.dump(yaml.safe_load(document), explicit_start=False), file=fh)
