#!/usr/bin/python3

wf = 0
if wf:
    max_team = 152
    max_human_judge = 12
    max_pc2_autojudge = 0
    max_kattis_autojudge = 16
    max_domjudge = 16
    max_domjudge_ccsadmin = 5
    max_ccsadmin = 5
else:
    # nac2022
    max_team = 53
    max_human_judge = 12
    max_pc2_autojudge = 0
    max_kattis_autojudge = 0
    max_domjudge = 0
    max_domjudge_ccsadmin = 0
    max_ccsadmin = 0


def print_host(num, hostname, ip, yaml_fh, list_fh, base_ip=0):
    print(f"    {hostname}{num}:\n      ansible_host: {ip}.{base_ip+num}", file=yaml_fh)
    print(f"{hostname}{num}", file=list_fh)


def print_server(hostname, ip, yaml_fh):
    print(f"    {hostname}:\n      ansible_host: {ip}", file=yaml_fh)


if __name__ == "__main__":
    with open("../hosts.yml", "wt") as fh:
        print(
            """---
contestants:
  hosts:""",
            file=fh,
        )
        with open("../list.team", "wt") as list_fh:
            for i in range(max_team):
                print_host(i + 1, "team", "10.0.0", fh, list_fh)
        print(
            """judges:
  hosts:""",
            file=fh,
        )
        with open("../list.judge", "wt") as list_fh:
            for i in range(max_human_judge):
                print_host(i + 1, "judge", "10.2.2", fh, list_fh)
        with open("../list.autojudges", "wt") as list_fh:
            for i in range(max_kattis_autojudge):
                print_host(i + 1, "autojudge", "10.2.2", fh, list_fh, 31)
        with open("../list.pc2judges", "wt") as list_fh:
            for i in range(max_pc2_autojudge):
                print_host(i + 1, "pc2-aj", "10.2.2", fh, list_fh, 143)
        with open("../list.domjudges", "wt") as list_fh:
            for i in range(max_domjudge):
                print_host(i + 1, "domjudge-judgehost", "10.2.2", fh, list_fh, 192)
        print(
            """others:
  hosts:""",
            file=fh,
        )
        with open("../list.domjudges_ccsadmin", "wt") as list_fh:
            for i in range(max_domjudge_ccsadmin):
                print_host(i + 1, "domjudge-ccsadmin", "10.3.3", fh, list_fh, 222)
        with open("../list.ccsadmin", "wt") as list_fh:
            for i in range(max_ccsadmin):
                print_host(i + 1, "-ccsadmin", "10.3.3", fh, list_fh, 231)
        print_server("squidserver", "10.3.3.205", fh)
        # print_server("media", "10.3.3.206", fh);
        print_server("cds", "10.3.3.207", fh)
        print_server("scoreboard", "10.3.3.208", fh)
        print_server("packages", "10.3.3.209", fh)
        print_server("backup", "10.3.3.210", fh)
        print_server("authprint", "10.3.3.211", fh)
        # print_server("kattis", "10.3.3.212", fh)
        # print_server("kattisbackup", "10.3.3.213", fh)
        print_server("squidserver", "10.3.3.214", fh)
        # print_server("pc2-shadowccs", "10.3.3.215", fh);
        # print_server("domserver", "10.3.3.216", fh)
        print(
            """ldapserver:
  hosts:
    ldap-server1:
      ansible_host: 10.3.3.211
  hosts:
    ldap-server2:
      ansible_host: 10.3.3.210""",
            file=fh,
        )
