#!/usr/bin/python

from passlib.hash import sha512_crypt
from getpass import getpass

def input_passwd():
    pw, conf = getpass("Password: "), getpass("Confirm: ")
    if pw != conf:
        print("Does not match!")
        exit(1)

    return pw

def main():
    pw = input_passwd()
    shadow_hash = sha512_crypt.hash(pw)
    print(shadow_hash)

main()

# vim: set ts=4 sw=4 et syn=python
