#!/usr/bin/python

import string
from random import SystemRandom
from crypt import crypt
from getpass import getpass

def get_salt(saltlen):
    copts = string.ascii_letters + string.digits
    sysrand = SystemRandom()
    salt = ""
    for i in range(saltlen):
        salt += sysrand.choice(copts)

    return salt

def input_passwd():
    pw, conf = getpass("Password: "), getpass("Confirm: ")
    if pw != conf:
        print("Does not match!")
        exit(1)

    return pw

def crypt_passwd(pw, salt):
    return crypt(pw, "$6${0}$".format(salt))

def main():
    salt = get_salt(8)
    pw = input_passwd()
    cpw = crypt_passwd(pw, salt)
    print(cpw)

main()

# vim: set ts=4 sw=4 et syn=python
