#!/usr/bin/python

import string
from random import SystemRandom
from crypt import crypt
from getpass import getpass


def input_crypt():
    pwhash = getpass("pwhash: ")
    return pwhash

def input_passwd():
    pw = getpass("Password: ")
    return pw

def crypt_passwd(pwhash, pw):
    return crypt(pw, pwhash)

def main():
    pwhash = input_crypt()
    pw = input_passwd()
    cpw = crypt_passwd(pwhash, pw)
    if cpw == pwhash:
        print("Matching")
    else:
        print("no match")

main()

# vim: set ts=4 sw=4 et syn=python
