---
- name: Copy per contest hosts to /etc/hosts on backup
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/hosts
    mode: '0644'
  with_first_found:
    - files/hosts.{{ contest }}.new
    - files/hosts.new
  notify: Restart dnsmasq
  when: inventory_host == 'backup'

- name: Copy per contest hosts to /etc/hosts on non-backup
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/hosts
    mode: '0644'
  with_first_found:
    - files/hosts.{{ contest }}.new
    - files/hosts.new
  when: inventory_host != 'backup'
