---
- name: Set the git home directory
  ansible.builtin.set_fact:
    git_home_dir: /srv/git

- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure git group
  ansible.builtin.group:
    name: "git"
    gid: 1005
    state: present

- name: Ensure git user
  ansible.builtin.user:
    name: "git"
    password: "{{ git_user_password }}"
    shell: /usr/bin/git-shell
    group: git
    home: "{{ git_home_dir }}"
    create_home: true
    state: present

- name: Ensure ~git/git-shell-commands exists
  ansible.builtin.file:
    path: "{{ git_home_dir }}/git-shell-commands"
    owner: git
    group: git
    state: directory
    mode: "0755"

- name: Ensure no-interactive-login is installed
  ansible.builtin.copy:
    src: files/no-interactive-login
    dest: "{{ git_home_dir }}/git-shell-commands/no-interactive-login"
    owner: git
    group: git
    mode: "0755"

- name: Ensure the .ssh directory exists
  ansible.builtin.file:
    path: "{{ git_home_dir }}/.ssh"
    mode: "0700"
    state: directory
    owner: git
    group: git

# TODO: there's probably an authorized keys ansible task
- name: Ensure git user .ssh authorized_keys is installed
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "{{ git_home_dir }}/.ssh/authorized_keys"
    owner: git
    group: git
    mode: "0600"

- name: Make git user hushlogin
  ansible.builtin.file:
    path: "{{ git_home_dir }}/.hushlogin"
    owner: git
    group: git
    mode: "0600"
    state: touch
    modification_time: preserve
    access_time: preserve


# Clone a set of repositories and make them available
- name: Create key files
  ansible.builtin.copy:
    dest: "{{ git_home_dir }}/.ssh/git-privatekey-{{ item.name }}"
    owner: git
    group: git
    mode: "0600"
    content: "{{ lookup('file', item.deploy_key) }}\n"
  no_log: true
  diff: false
  loop: "{{ gitserver_repos }}"

- name: Clone/update repositories
  ansible.builtin.git:
    repo: "{{ item.remote }}"
    dest: "{{ git_home_dir }}/{{ item.name }}.git"
    version: master
    bare: true
    key_file: "{{ git_home_dir }}/.ssh/git-privatekey-{{ item.name }}"
    accept_newhostkey: true # does trust-on-first-use
  become: true
  become_user: git
  loop: "{{ gitserver_repos }}"

- name: Configure the key properly in the repo for manual commands
  community.general.git_config:
    name: core.sshCommand
    value: "ssh -i ~/.ssh/git-privatekey-{{ item.name }}"
    scope: "local"
    repo: "{{ git_home_dir }}/{{ item.name }}.git"
  become: true
  become_user: git
  loop: "{{ gitserver_repos }}"
