- name: Create coachview user
  ansible.builtin.user:
    name: cv
    home: /cv
    uid: 17263
    shell: "/usr/bin/bash"

- name: Add run script for coachview
  ansible.builtin.template:
    src: coachview_run.sh.j2
    dest: /cv/run
    owner: cv
    group: cv
    mode: '0755'

- name: Add .xsessionrc script for coachview
  ansible.builtin.copy:
    content: |
      /cv/run
      exit 0
    dest: /cv/.xsessionrc
    owner: cv
    group: cv
    mode: '0755'

- name: Enable autologin to user coachview
  ansible.builtin.copy:
    content: |
      [SeatDefaults]
      # Autologin
      autologin-user=cv
      autologin-timeout=0
    dest: /etc/lightdm/lightdm.conf.d/coachview.conf
    owner: root
    group: root
    mode: '0644'

- name: Check if coachview is installed
  ansible.builtin.stat:
    path: /cv/coachview.sh
  register: coachview

- name: Download coachview
  github_release:
    repo: icpctools/icpctools
    asset: "^coachview-.*\\.zip$"
    version: "{{ coachview_version }}"
    dest: /cv/coachview.zip
  when: false

- name: Copy coachview zip
  ansible.builtin.copy:
    src: files/coachview.zip
    dest: /cv/coachview.zip
    mode: '0644'

- name: Unpack the client
  ansible.builtin.unarchive:
    remote_src: true
    src: /cv/coachview.zip
    dest: /cv/
    owner: cv
    group: cv

- name: Check if coachview is currently running
  ansible.builtin.command: pgrep --uid cv
  register: cv_running
  ignore_errors: true
  changed_when: false

- name: Restart lightdm
  ansible.builtin.systemd:
    name: lightdm
    state: restarted
  when: cv_running.rc != 0
