- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk
    version: 21.0.0
    state: present
  when: not skip_chocolatey

- name: Install vlc
  chocolatey.chocolatey.win_chocolatey:
    name: vlc
    state: present
  when: not skip_chocolatey

- name: Fetch coachview
  ansible.windows.win_copy:
    src: files/coachview-{{ coachview_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/coachview-{{ coachview_version }}.zip

- name: Unzip coachview
  community.windows.win_unzip:
    src: /Users/{{ ansible_user }}/Desktop/coachview-{{ coachview_version }}.zip
    dest: /Users/{{ ansible_user }}/Desktop/coachview
    remote_src: true
    creates: /Users/{{ ansible_user }}/Desktop/coachview

- name: Add bat script to launch the coachview admin
  ansible.windows.win_copy:
    content: >
      c:/users/{{ ansible_user }}/desktop/coachview/coachView.bat
      {{ coachview_cds_url }}
      {{ coachview_user }} {{ coachview_pass }}
    dest: /users/{{ ansible_user }}/desktop/launch_coachview_admin.bat

- name: Copy a shortcut to launch the coachview client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/launch_coachview_admin.bat"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/coachview.lnk"

- name: Configure dns to point to the magic new coachview-server
  ansible.windows.win_shell: |
    Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses ("172.36.0.207")
