# Download latest version from DOMjudge repo
# Alternative is to put the correct file in /tmp and set internet to false
- name: Download turboboost script
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/DOMjudge/domjudge-scripts/main/provision-contest/disable-turboboost_ht
    dest: /tmp/turboboost_ht
    mode: 0777
  when: internet

- name: Install turboboost script
  ansible.builtin.copy:
    src: /tmp/turboboost_ht
    dest: /usr/sbin/disable_turboboost_ht
    owner: root
    group: root
    mode: 0755

- name: Set hyperthreading service
  ansible.builtin.copy:
    src: turboboost_ht.service
    dest: /lib/systemd/system/turboboost_ht.service
    owner: root
    group: root
    mode: 0644

- name: Disable hyperthreading
  ansible.builtin.systemd:
    name: turboboost_ht
    state: started
    enabled: true
    daemon_reload: true
