---
- name: Add taskset to most run scripts
  ansible.builtin.lineinfile:
    path: /usr/local/bin/{{ item }}
    state: present
    regexp: '^([ ]*)(java|kotlin|pypy)(.*)$'
    backrefs: true
    line: '\1taskset -c 2 \2\3'
  loop:
    - runpython3
    - runkotlin
    - runjava

- name: Add taskset to runc/runcpp
  ansible.builtin.lineinfile:
    path: /usr/local/bin/{{ item }}
    state: present
    regexp: '^(./a.out)(.*)$'
    backrefs: true
    line: 'taskset -c 2 \1\2'
  loop:
    - runc
    - runcpp
