ntp_hosts:
  - 172.29.1.20"
  - 10.3.3.208"
  - 10.3.3.209"
  - 0.ubuntu.pool.ntp.org"
  - 1.ubuntu.pool.ntp.org"
  - 2.ubuntu.pool.ntp.org"
  - 3.ubuntu.pool.ntp.org"
fallback_ntp_hosts:
  - 172.29.1.20"
  - 10.3.3.208"
  - 10.3.3.209"
  - 0.ubuntu.pool.ntp.org"
  - 1.ubuntu.pool.ntp.org"
  - 2.ubuntu.pool.ntp.org"
  - 3.ubuntu.pool.ntp.org"
extra_nic_configs:
  - gateway: false
    address: 10.3.3.210/24
    ifc_name: enp0s31f6
    routes:
      - { network: 10.0.0.0/8, via: 10.3.3.254 }
# TODO update this
green_network_ifc: enp0s0

# script server config below here:
script_server_url: files/script-server.zip

script_server_admin_users: &admin_users
  # hostnames or ips
  - backup
  - 127.0.0.1

script_server_commands:
  - name: run-lastminute
    description: Runs lastminute.yml
    group: ansible # for organization in script-server
    content: |
      #!/usr/bin/bash -ex
      cd /root/ansible
      ansible-playbook --limit "$PARAM_HOSTNAME" lastminute.yml
    parameters:
      - name: hostname
        env_var: PARAM_HOSTNAME
        type: text
        default: ${auth.audit_name}
        constant: true
        required: true

  - name: refresh-git
    description: Update git on the CDS
    group: cds
    allowed_users: &cds_allowed_users
      - cds-wf46 # cds host
      - cds-wf47 # cds host
      - cdsadmin1
      - cdsadmin2
      - cdsadmin3
    content: |
      #!/usr/bin/bash -ex
      ssh root@cds "bash -ec 'set -x; cd /mnt/cds-wf46/cds/contest_repo && sudo -u cds git pull'"
    parameters: []

  - name: status-cds
    description: Show service status of cds instances
    group: cds
    allowed_users: *cds_allowed_users
    content: |
      #!/usr/bin/bash -ex
      for x in $CDS_INSTANCE; do
        ssh root@cds systemctl status $CDS_INSTANCE
      done
    parameters:
      - name: instance
        env_var: CDS_INSTANCE
        type: multiselect
        required: true
        separator: ' '
        values: &cds_instances
          - cds-wf46
          - cds-wf47
          - p100-wf46
          - p100-wf47

  - name: restart-cds
    description: Restarts cds and p100 instances
    group: cds
    allowed_users: *cds_allowed_users
    content: |
      #!/usr/bin/bash -ex
      for x in $CDS_INSTANCE; do
        ssh root@cds systemctl restart $CDS_INSTANCE
      done
    parameters:
      - name: instance
        env_var: CDS_INSTANCE
        type: multiselect
        required: true
        separator: ' '
        values: *cds_instances
