---
extra_nic_configs:
  - gateway: false
    address: 10.3.3.207/24
    ifc_name: enp0s31f6
    routes:
      - {network: 10.0.0.0/8, via: 10.3.3.254}

cds_version: 2.5.984
cds_contest_git_repo: /mnt/cds-wf46/git/wfluxor.git
# cds_contest_git_repo: git@cds-wf46:/wfluxor.git

cds_config:
  cds-wf46:
    http_port: 8046
    https_port: 8446
    contests: &contests_wf46
      - name: systest0-wf46
        path: wf46/systest0
        # ccs:
        #   url: https://domjudge.nac.icpc.global/api/contests/NAC-2023-real
        #   username: cds
        #   password: hungry-SACRIFICE-LITIGATE-COHERENT
    # Path to a yaml file inside vars/ containing an accounts array
    accounts: cds/cds-accounts.yaml
  cds-wf47:
    http_port: 8047
    https_port: 8447
    contests: &contests_wf47
      - name: systest0-wf47
        path: wf47/systest0
    accounts: cds/cds-accounts.yaml
  p100-wf46:
    http_port: 9046
    https_port: 9446
    contests: *contests_wf46
    accounts: cds/p100-accounts.yaml
  p100-wf47:
    http_port: 9047
    https_port: 9447
    contests: *contests_wf47
    accounts: cds/p100-accounts.yaml
