---
extra_nic_configs:
  # Blue
  - gateway: false
    address: 10.3.3.207/24
    ifc_name: enp0s31f6
    routes:
      - {network: 10.0.0.0/8, via: 10.3.3.254}
  # Green
  - gateway: 172.29.0.1
    address: 172.29.1.207/22
    ifc_name: enx0050b623c30d
    routes: []
  # Red
  - gateway: false
    address: 172.24.0.7/24
    ifc_name: enx0050b623c689
    routes: []

cds_version: 2.5.991
cds_contest_git_repo: git@cds-wf46:/wfluxor.git

cds_config:
  cds-wf46:
    http_port: 8046
    https_port: 8446
    contests: &contests_wf46
      - name: systest0-wf46
        path: wf46/systest0
        # ccs:
        #   url: https://domjudge.nac.icpc.global/api/contests/NAC-2023-real
        #   username: cds
        #   password: hungry-SACRIFICE-LITIGATE-COHERENT
      - name: finals-wf46
        path: wf46/finals
        id: wf46_finals
        record_reactions: true
        video:
          desktop: http://team{0}:9090
          webcam: http://team{0}:8080
        ccs:
          url: https://domjudge-wf46/api/contests/wf46_finals
          username: cds
          password: riot-unsnap-coffee-racing
    # Path to a yaml file inside vars/ containing an accounts array
    accounts: cds/cds-accounts.yaml
    domains: &cds_domains
      - - matveyAdmin
        - matvey
      - - presAdmin
        - presentation
        - balloon
        - coachview
        - deboer
        - david
        - nicky
        - mattias
  cds-wf47:
    http_port: 8047
    https_port: 8447
    contests: &contests_wf47
      - name: systest0-wf47
        path: wf47/systest0
    accounts: cds/cds-accounts.yaml
  p100-wf46:
    http_port: 9046
    https_port: 9446
    contests: *contests_wf46
    accounts: cds/p100-accounts.yaml
  p100-wf47:
    http_port: 9047
    https_port: 9447
    contests: *contests_wf47
    accounts: cds/p100-accounts.yaml
