---
extra_nic_configs:
  - gateway: false
    address: 10.3.3.211/24
    ifc_name: enp0s31f6
    routes:
      - { network: 10.0.0.0/8, via: 10.3.3.254 }
  - gateway: 172.29.0.1
    address: 172.29.1.211/22
    ifc_name: enx00e04c68ff12
