name: Verify last minute flow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/ansible/creator-ee:v24.2.0
      options: "--entrypoint /bin/bash"
    steps:
      - uses: actions/checkout@v2
      - name: Install python3-passlib
        run: /usr/bin/apt install -y python3-passlib
      - name: Install the requirements
        run: /usr/local/bin/ansible-galaxy install -r requirements.yml
      - name: run ansible lint
        run: /usr/local/bin/ansible-lint -c .config/ansible-lint.yml
        env:
          # These tell ansible-lint to use github compatible annotation format:
          GITHUB_ACTIONS: "true"
          GITHUB_WORKFLOW: "{{ github.workflow.name }}"
