name: Verify last minute flow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/ansible/creator-ee:v0.4.1
      options: "--entrypoint /bin/bash"
    steps:
      - uses: actions/checkout@v2
      - name: run ansible lint
        run: /usr/local/bin/ansible-lint -vvv
        env:
          # These tell ansible-lint to use github compatible annotation format:
          GITHUB_ACTIONS: "true"
          GITHUB_WORKFLOW: "{{ github.workflow.name }}"
