- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk
    version: 21.0.0
    state: present
  when: not skip_chocolatey

- name: Download presentation zip
  github_release:
    repo: icpctools/icpctools
    asset: "^presentationAdmin-.*\\.zip$"
    version: "{{ presadmin_version }}"
    dest: files/presentationAdmin.zip
  delegate_to: localhost
  register: github_presadmin

- name: Download presentation admin
  ansible.windows.win_copy:
    src: github_presadmin.cache_path
    dest: /Users/{{ ansible_user }}/Desktop/presentationAdmin.zip

- name: Unzip presentation admin
  community.windows.win_unzip:
    src: "{{ github_presadmin.cache_path }}"
    dest: /Users/{{ ansible_user }}/Desktop/presadmin
    creates: /Users/{{ ansible_user }}/Desktop/presadmin

- name: Add bat script to launch the presentation admin
  ansible.windows.win_copy:
    content: >
      c:/users/{{ ansible_user }}/desktop/presadmin/presAdmin.bat
      {{ presadmin_cds_url }}
      {{ presadmin_user }} {{ presadmin_pass }}
    dest: /users/{{ ansible_user }}/desktop/launch_pres_admin.bat

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/launch_pres_admin.bat"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/presadmin.lnk"
