- name: Install jre
  chocolatey.chocolatey.win_chocolatey:
    name: openjdk11jre
    state: present
  when: not skip_chocolatey

- name: Update/download and install the presentation client
  block:
    - name: Get prerelease version
      delegate_to: 127.0.0.1
      ansible.builtin.uri:
        url: https://api.github.com/repos/icpctools/icpctools/releases?per_page=3
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: latest_presentation_release_array
      when: presadmin_version is not defined

    - name: Set presentation admin latest version
      ansible.builtin.set_fact:
        presadmin_version: "{{ latest_presentation_release_array.json[0].name | replace('v', '') }}"
      when: presadmin_version is not defined

    - name: Download presentation admin
      ansible.windows.win_get_url:
        url: https://github.com/icpctools/icpctools/releases/download/v{{ presadmin_version }}/presentationAdmin-{{ presadmin_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/presentationAdmin-{{ presadmin_version }}.zip

    - name: Unzip presentation admin
      community.windows.win_unzip:
        src: /Users/{{ ansible_user }}/Desktop/presentationAdmin-{{ presadmin_version }}.zip
        dest: /Users/{{ ansible_user }}/Desktop/presadmin
        remote_src: true
        creates: /Users/{{ ansible_user }}/Desktop/presadmin

- name: Add bat script to launch the presentation admin
  ansible.windows.win_copy:
    content: >
      c:/users/{{ ansible_user }}/desktop/presadmin/presAdmin.bat
      {{ presadmin_cds_url }}
      {{ presadmin_user }} {{ presadmin_pass }}
    dest: /users/{{ ansible_user }}/desktop/launch_pres_admin.bat

- name: Copy a shortcut to launch the presentation client
  community.windows.win_shortcut:
    src: "c:/Users/{{ ansible_user }}/Desktop/launch_pres_admin.bat"
    dest: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup/presadmin.lnk"
